Jenkinsfile
org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/AbstractXtendInstallDebugInfoMojo.java
org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/XtendCompilerMojoIT.java
org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/XtendCompilerMojoTraceIT.java
org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/XtendInstallDebugInfoMojoIT.java
pom.xml

reactivated xtend maven plugin and archetype. #17

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/imports/RewritableImportSectionTests.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/imports/RewritableImportSectionTest0.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/imports/RewritableImportSectionTest1.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/imports/RewritableImportSectionTest2.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/compiler/ResolvingCrossReferenceDuringIndexingTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/compiler/ResolvingCrossReferenceDuringIndexingTest.java
org.eclipse.xtext.tycho.tests.parent/pom.xml

enabled more test name patterns

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/build/XtendIncrementalBuilderTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/build/XtendIncrementalBuilderTest.java
org.eclipse.xtext.tycho.parent/pom.xml

test for https://github.com/eclipse/xtext-extras/issues/30

test for https://github.com/eclipse/xtext-extras/issues/30

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/JavaRefactoringIntegrationTest.java

Tests for https://github.com/eclipse/xtext-eclipse/issues/76

Tests for https://github.com/eclipse/xtext-eclipse/issues/76

---

gradle/eclipse-project-layout.gradle
gradle/java-compiler-settings.gradle

Consistent use of tabs instead of spaces
Use single whitespace between brackets

[format] Streamlined whitespaces

---

org.eclipse.xtend.core/.classpath
org.eclipse.xtend.ide.common/.classpath

[#40] Ignore optional compile problems on *-gen source folders

---

org.eclipse.xtext.target/org.eclipse.xtext.target.target

always use latest greatest mwe2 version. solves #46

always use latest greatest mwe2 version. solves #46

---

org.eclipse.xtend.gwt.feature/feature.xml
org.eclipse.xtend.sdk.feature/feature.xml

Signed-off-by: Moritz Eysholdt <moritz.eysholdt@typefox.io>

fixed #52: Xtend must not package plugins/features from Xtext

---

Jenkinsfile
org.eclipse.xtext.parent/pom.xml

Signed-off-by: Moritz Eysholdt <moritz.eysholdt@typefox.io>

[releng] deploy to build/maven-repository, don't use it as local repo

---

Jenkinsfile

Signed-off-by: Moritz Eysholdt <moritz.eysholdt@typefox.io>

clean 'build' folder

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBug440006Test.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/richstring/RichStringCompilerTest.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/XtendValidationTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBug440006Test.java

[440006] added tests for rich string validation and compilation 
xtend tests for https://github.com/eclipse/xtext-extras/pull/31

[440006] added tests for rich string validation and compilation 

---

org.eclipse.xtext.tycho.parent/pom.xml
pom.xml

fixed maven hierarchy

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/Bug415030Test.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/Bug462915Test.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/contentassist/Bug415030Test.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/contentassist/Bug462915Test.java
org.eclipse.xtend.ide/templates/templates.xml

[462915] reactivated template proposals / tests
second half of https://github.com/eclipse/xtext-eclipse/pull/67
Signed-off-by: Christian Dietrich christian.dietrich@itemis.de

[462915] reactivated template proposals / tests

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/wizards/Messages.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/wizards/NewXtendClassWizardPage.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/wizards/XtendTypeCreatorUtil.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/wizards/messages.properties

Option added like in JDT's class wizard:
Created file:

[378821] Add option to generate main method

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/formatting2/RichStringFormatter.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/SemanticText.java

Typo in class name fixed

---

.gitignore
.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtend.core.tests/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtend.core/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtend.ide.common/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtend.idea.tests/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtend.idea/.settings/org.eclipse.buildship.core.prefs

connection.project.dir changed to composite build location in new
umbrella project
value 'containers' added by Buildship

Gradle composite

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBug440906Test.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBug457346Test.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/OverloadedExtensionCompilerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/Bug464136Test.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBug440906Test.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBug457346Test.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/OverloadedExtensionCompilerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/Bug464136Test.java

[#6] fixed some tests after java 8 migration

[#6] fixed some tests after java 8 migration

---

org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/Bug446364Processor.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/ASTParserFactory.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/declaration/AnnotationReferenceBuildContextImpl.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/declaration/PrimitiveTypeImpl.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/highlighting/XtendSyntaxColoringPreferencePage.java
org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/highlighting/XtendHighlightingLexer.java

[501975] Null guard for switch statements

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/Xtend.xtext

Resolved warnings for overridden rules

Added missing Override annotations

---

org.eclipse.xtend.caliper.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.core.tests.java8/META-INF/MANIFEST.MF
org.eclipse.xtend.core.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/projects/xtend-annotation-examples-client/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/projects/xtend-examples/META-INF/MANIFEST.MF
org.eclipse.xtend.ide.swtbot.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.ide.tests.data/META-INF/MANIFEST.MF
org.eclipse.xtend.ide.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.performance.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.swtbot/META-INF/MANIFEST.MF

[502897] Streamlined plugin metadata

---

org.eclipse.xtend.core.tests/longrunning/src/org/eclipse/xtend/core/tests/compiler/batch/XtendCompilerAntTaskTest.java
org.eclipse.xtend.core.tests/pom.xml

filtered features from ant classpath. fixes #87

filtered features from ant classpath. fixes #87

---

org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/TemplateWhitespace.java

[489237] Optimized equals/hashCode implementation

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/XtendValidationTest.java

[381031] Add test case testUnusedFunction_1

---

Jenkinsfile
org.eclipse.xtend.maven.plugin/pom.xml
org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/XtendCompilerMojoIT.java
org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/XtendCompilerMojoTraceIT.java
org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/XtendInstallDebugInfoMojoIT.java

Fixed Xtend*IT. Solves #92

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/javaconverter/ASTParserFactory.xtend
org.eclipse.xtend.core/src/org/eclipse/xtend/core/javaconverter/JavaConverter.xtend
org.eclipse.xtend.core/src/org/eclipse/xtend/core/linking/Linker.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/richstring/AbstractRichStringPartAcceptor.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/richstring/IRichStringPartAcceptor.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/ASTParserFactory.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/JavaConverter.java

Fixed Javadoc issues

---

org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/XtendInstallDebugInfoMojoIT.java

Adjust test expectation

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/editor/Bug493784Test.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/editor/Bug493784Test.java

Replacement for PR eclipse/xtext-xtend#101 due to problems on the build server with branch names containing /

[493784] Add test for bug493784

---

gradle/versions.gradle

fixed ideaGradlePluginVersion => 1.0.15

fixed ideaGradlePluginVersion

---

gradle/versions.gradle

Signed-off-by: Holger Schill <Holger.Schill@itemis.de>

Align version number of jdt.core

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/Bug464136Test.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/Bug464136Test.java

fixed broken test after eclipse -> gradle move. fixes #123

fixed broken test after eclipse -> gradle move. fixes #123

---

org.eclipse.xtend.caliper.tests/.classpath
org.eclipse.xtend.caliper.tests/build.properties
org.eclipse.xtend.caliper.tests/src/org/eclipse/xtend/caliper/tests/typesystem/newImpl/UnitTest.java
org.eclipse.xtend.caliper.tests/testdata/org/eclipse/xtend/core/tests/typesystem/CharIterable.java
org.eclipse.xtend.caliper.tests/testdata/org/eclipse/xtend/core/tests/typesystem/MapType.java
org.eclipse.xtend.caliper.tests/testdata/org/eclipse/xtend/core/tests/typesystem/RawIterable.java
org.eclipse.xtend.caliper.tests/testdata/org/eclipse/xtend/core/tests/typesystem/StringIntMap.java
org.eclipse.xtend.caliper.tests/testdata/test/InnerClasses.java
org.eclipse.xtend.ide.tests.data/src/test/Annotation.java
org.eclipse.xtend.ide.tests.data/src/test/Annotation2.java
org.eclipse.xtend.ide.tests.data/src/test/Enum1.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/AbstractReusableActiveAnnotationTests.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/ActiveAnnotationsProcessingInIDETest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/AbstractReusableActiveAnnotationTests.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/ActiveAnnotationsProcessingInIDETest.java

Fix Tests #125 #127

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/codebuilder/ClassBuilders.xtend
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/codebuilder/InterfaceBuilders.xtend
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/quickfix/CreateXtendTypeQuickfixes.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/codebuilder/AbstractClassBuilder.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/codebuilder/AbstractInterfaceBuilder.java

[434691] Harmonize icons in Xtend Quickfix

[434691] Harmonize icons in Xtend Quickfix

---

org.eclipse.xtend.ide/src-gen/org/eclipse/xtend/ide/AbstractXtendUiModule.java

[415677] Language Specific Compare Viewer title
- regenerated xtend

[415677] Language Specific Compare Viewer title

---

gradle/developers.gradle

fixed invalid developers.gradle. resolves https://github.com/eclipse/xtext-extras/pull/119

fixed invalid developers.gradle. 

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/Bug440858Test.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/contentassist/Bug440858Test.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/contentassist/XtendProposalProvider.java

[440858] Add Override Proposals inside Inner Classes of Annotations

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/build/XtendIncrementalBuilderTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/OverrideValidationTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/build/XtendIncrementalBuilderTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/IssueCodes.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/quickfix/XtendQuickfixProvider.java

[364298] Added Validation for Override annotation

[364298] Added Validation for Override annotation

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/AbstractXtendTestCase.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/ModifierValidationTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/XtendValidationTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/ModifierValidationTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java

[402933] added some more validation for abstract methods

[402933] added some more validation for abstract methods

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/OverrideValidationTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/IssueCodes.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/codebuilder/MethodBuilderTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/codebuilder/MethodBuilderTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/codebuilder/MemberFromSuperImplementor.xtend
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/codebuilder/MethodBuilders.xtend
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/quickfix/XtendQuickfixProvider.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/codebuilder/AbstractMethodBuilder.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/codebuilder/JavaMethodBuilder.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/codebuilder/MemberFromSuperImplementor.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/codebuilder/XtendMethodBuilder.java

[418504] Override Tester: Check for Synchronized

[418504] Override Tester: Check for Synchronized

---

releng/org.eclipse.xtend.maven.parent/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

Updated Tycho to Version 1.0.0

Updated Tycho to Version 1.0.0

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/EclipseIssue219Test.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/contentassist/EclipseIssue219Test.java

test for https://github.com/eclipse/xtext-eclipse/issues/219

test for https://github.com/eclipse/xtext-eclipse/issues/219

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/XtendFormatterBugTests.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendFormatterBugTests.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/formatting2/XtendFormatter.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/XtendFormatter.java

[403823][403340] Fixed Problem with bogus ifelse multiline formatting

[403823][403340] Fixed Problem with bogus ifelse multiline formatting

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/jvmmodel/XtendJvmModelInferrer.java
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/JavaRefactoringIntegrationTest.java

[489208] fixed problem of refactoring anon inner classes

[489208] fixed problem of refactoring anon inner classes

---

org.eclipse.xtend.ide.common/src/org/eclipse/xtend/ide/common/highlighting/XtendHighlightingCalculator.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/highlighting/XtendHighlightingCalculatorTest.java

Fixed IAE in XtendHighlightingCalculator #184

Fixed IAE in XtendHighlightingCalculator #184

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/AnnotationPropertyTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/AnnotationPropertyTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/ToAnno.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/ToAnnoProcessor.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/declaration/JvmBasedDeclarations.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/declaration/JvmAnnotationTypeElementDeclarationImpl.java

added support for creating annotation properties in xtend active annotations #200

added support for creating annotation properties in xtend active annotations

---

org.eclipse.xtend.ide.swtbot.tests/swtbot/src/org/eclipse/xtend/ide/tests/RenameXtendClassBug516096SwtBotTest.xtend
org.eclipse.xtend.ide.swtbot.tests/swtbot/src/org/eclipse/xtend/ide/tests/SwtBotProjectHelper.xtend
org.eclipse.xtend.ide.swtbot.tests/swtbot/xtend-gen/org/eclipse/xtend/ide/tests/RenameXtendClassBug516096SwtBotTest.java
org.eclipse.xtend.ide.swtbot.tests/swtbot/xtend-gen/org/eclipse/xtend/ide/tests/SwtBotProjectHelper.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/refactoring/XtendRenameStrategy.java

[516096] fixed file renaming with spaces in path

[516096] fixed file renaming with spaces in path

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/XtendValidationTest.java
org.eclipse.xtend.core.tests/testdata/testdata/Annotation6.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java

fixed broken annotation target type validation with fields in xtend-annotations #206

 fixed broken annotation target type validation with fields in xtend-annotations #206

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/declaration/JvmBasedDeclarations.xtend
org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/declaration/JvmCommon.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/declaration/JvmTypeParameterDeclarationImpl.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/declaration/TypeParameterDeclarationImpl.java

[516571] ClassCastException in getTypeParameterDeclarator

[516571] ClassCastException in getTypeParameterDeclarator

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/contentassist/XtendProposalProvider.java

fixed ClassCastException preventing Type Proposals in fields from working #218

fixed ClassCastException preventing Type Proposals in fields from working

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/highlighting/XtendHighlightingCalculatorTest.java

[409297][hightlighting][deprecation] Semantics different from JDTs

[409297][hightlighting][deprecation] Semantics different from JDTs

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/contentassist/TemplateProposalProvider.java

[462922] [xtend] Show templates before keywords

[462922] [xtend] Show templates before keywords

---

.project
org.eclipse.xtend.core.tests.java8/.project
org.eclipse.xtend.core.tests/.project
org.eclipse.xtend.core/.project
org.eclipse.xtend.ide.common/.project
org.eclipse.xtend.idea/.project

gradleprojectbuilder added by Buildship project import

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/XtendUiModule.xtend
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/XtendUiModule.java

[496665] bind XbaseResourceForEditorInputFactory for all xbase languages

[496665] bind XbaseResourceForEditorInputFactory for all xbase languages

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/XtendUiModule.xtend
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/builder/XtendParallelBuilderParticipant.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/XtendUiModule.java

cleanup ishouldgenerate/builderparticipant.shouldgenerate #232

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/Bug467063Test.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/AddInterfaceWithDefault.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/AddInterfaceWithDefaultProcessor.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/Bug467063Test.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/compiler/batch/XtendCompilerTester.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/declaration/JvmBasedDeclarations.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/declaration/MutableJvmMethodDeclarationImpl.java

[467063] allow creating default methods from active annotations

[467063] allow creating default methods from active annotations

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/Issue242Test.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/contentassist/Issue242Test.java

added tests for #242

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/XtendRuntimeModule.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/XtendRuntimeModule.java

[490371] [xbase] Bind JvmModelTargetURICollector by default for all xbase languages

[490371] [xbase] Bind JvmModelTargetURICollector by default for all xbase languages

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/scoping/KnownTypesScope.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/scoping/XtendImportedNamespaceScopeProvider.java

[482758] Adedd null guards

---

org.eclipse.xtend.ide/plugin.xml
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/XtendUiModule.xtend
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/editor/XtendEditor.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/editor/XtendEditorAdapterFactory.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/view/DerivedSourceView.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/XtendUiModule.java

Provide adapter IShowInTargetList for the editor through adapter factory
Implemented IShowInTarget for DerivedSourceView
Removed bogus menu contribution (parameters are not supported)

[434688, 505760] Fixed 'Show In/ Generated Code'

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/imports/ImportOrganizerTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/imports/ImportOrganizerTest.java

tests for #246

---

org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF

added explicit dependency to equinox.common #253

added explicit dependency to equinox.common #253

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/AnnotationWithNestedEnum.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/AnnotationWithNestedEnumProcessor.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/AnnotationWithNestedEnumProcessorTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/AnnotationWithNestedEnumProcessor.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/AnnotationWithNestedEnumProcessorTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/declaration/AnnotationReferenceBuildContextImpl.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/declaration/AnnotationReferenceBuildContextImpl.java

[487559]  [active annotations] Set enum value on annotation with nested enum

[487559]  [active annotations] Set enum value on annotation with nested enum

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerXtendIssue256Test.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerXtendIssue256Test.java

fixed declaration of inline annotation in xtend fixes #256 

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/ModifierValidationTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/ValidationIssue265Test.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/ModifierValidationTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/ValidationIssue265Test.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java

Static Native method reporting error in version 2.13 #265

Static Native method reporting error in version 2.13 #265

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/quickfix/CodeBuilderQuickfix.xtend
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/quickfix/CodeBuilderQuickfix.java

Broken indent on create field in inner class #134

Broken indent on create field in inner class #134

---

org.eclipse.xtend.ide/plugin.xml
org.eclipse.xtend.ide/plugin.xml_gen

extension org.eclipse.core.contenttype.contentTypes for Xtend files
added.

[eclipse/xtext-eclipse#379] Contribute Content Type

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/FilteringClassLoader.xtend
org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/ProcessorInstanceForJvmTypeProvider.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/FilteringClassLoader.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/ProcessorInstanceForJvmTypeProvider.java

Fix broken aa class loading

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/compiler/batch/XtendBatchCompiler.java

dont resolve and validate type resources #290

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/editor/XtendEditorErrorTickUpdater.java

[526622] prevent NPE in XtendEditorErrorTickUpdater

[526622] prevent NPE in XtendEditorErrorTickUpdater

---

releng/org.eclipse.xtend.oxygen.target/.project
releng/org.eclipse.xtend.oxygen.target/org.eclipse.xtend.oxygen.target.target
releng/org.eclipse.xtend.oxygen.target/pom.xml
releng/org.eclipse.xtend.photon.target/.project
releng/org.eclipse.xtend.photon.target/org.eclipse.xtend.photon.target.target
releng/org.eclipse.xtend.photon.target/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml
tycho-pom.xml

added support for build with Photon and Oxygen

added support for build with Photon and Oxygen

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/Bug457681Test.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/JdtBasedProcessorProviderTest.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/MoreActiveAnnotationsTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/Bug457681Test.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/JdtBasedProcessorProviderTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/MoreActiveAnnotationsTest.java

removed unnec. deps from tests

---

org.eclipse.xtend.ide.swtbot.tests/swtbot/src/org/eclipse/xtend/ide/tests/AbstractRefactoringSwtBotTest.xtend
org.eclipse.xtend.ide.swtbot.tests/swtbot/xtend-gen/org/eclipse/xtend/ide/tests/AbstractRefactoringSwtBotTest.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/AbstractXtendUITestCase.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/compiler/batch/XtendCompilerAntTaskTest.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/ActiveAnnotationsProcessingInIDETest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/ActiveAnnotationsProcessingInIDETest.java

downstream changes for 
https://github.com/eclipse/xtext-eclipse/issues/439

downstream changes for 

---

org.eclipse.xtend.maven.plugin/pom.xml

made xbase dep explicit

---

org.eclipse.xtend.ide/plugin.xml

Fix highlighting in merge and compare view

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/WorkbenchTestHelper.java

added support for java 9 https://github.com/eclipse/xtext-core/issues/500

added support for java 9

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/javaconverter/JavaConverterTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/tasks/XtendTaskFinderTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/javaconverter/JavaConverterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/tasks/XtendTaskFinderTest.java

Fixed some Tests on Windows

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/ProcessorInstanceForJvmTypeProvider.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/ProcessorInstanceForJvmTypeProvider.java

[455102] made getClassloader public as it is public in subclasses anyway

[455102] made getClassloader public as it is public in subclasses anyway

---

org.eclipse.xtend.ide/src-gen/org/eclipse/xtend/ide/internal/XtendActivator.java

regenated example languages after j9 code generator changes

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/compiler/Bug456868Test.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/EclipseFileSystemTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/compiler/Bug456868Test.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/EclipseFileSystemTest.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/editor/XtendNatureAddingEditorCallback.java
org.eclipse.xtend.performance.tests/src/org/eclipse/xtend/performance/tests/PerformanceTest.xtend
org.eclipse.xtend.performance.tests/src/org/eclipse/xtend/performance/tests/PerformanceTestProjectSetup.java
org.eclipse.xtend.performance.tests/xtend-gen/org/eclipse/xtend/performance/tests/PerformanceTest.java

code cleanup (internal api and deprecation)

code cleanup (internal api and deprecation)

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/XtendValidationTest.java
org.eclipse.xtend.core.tests/testdata/testdata/DeprecatedClass.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java

Don't create Deprecation issues on imports if the top-level type is deprecated. #314

Don't create Deprecation issues on imports if the top-level type is deprecated. #314

---

org.eclipse.xtend.doc/contents/203_xtend_expressions.html
org.eclipse.xtend.doc/gen_eclipse_help.xml

regenerated docs

---

Jenkinsfile
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-luna.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

Fixed problem with Target Platforms not being properly installed
https://github.com/eclipse/xtext-eclipse/issues/472

Fixed problem with Target Platforms not being properly installed

---

org.eclipse.xtend.ide/.project
org.eclipse.xtend.m2e/.project
org.eclipse.xtend.standalone/.project

[eclipse/xtext#1156] Removed PDE API Tool configuration

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target

use oxygen sr2

---

build.gradle
gradle/eclipse-project-layout.gradle

[529291] Replace @build@ token in about.mappings

---

org.eclipse.xtend.core.tests.java8/src/org/eclipse/xtend/core/tests/java8/compiler/CompilerBug342021Test.xtend
org.eclipse.xtend.core.tests.java8/src/org/eclipse/xtend/core/tests/java8/compiler/Java8CompilerTest2.xtend
org.eclipse.xtend.core.tests.java8/xtend-gen/org/eclipse/xtend/core/tests/java8/compiler/CompilerBug342021Test.java
org.eclipse.xtend.core.tests.java8/xtend-gen/org/eclipse/xtend/core/tests/java8/compiler/Java8CompilerTest2.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/AnonymousClassCompilerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBug342021Test.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBugTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/ExtensionsCompilerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/XtendCompilerTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/AnonymousClassCompilerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBug342021Test.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBugTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/ExtensionsCompilerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/XtendCompilerTest.java

Change-Id: I70775edf03927fe3e4c139ad27103c928c5ac9c9
Signed-off-by: Arne Deutsch <arne@idedeluxe.com>

[bug-420984] Adapted failing tests to new compiler logic.

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/XtendUiModule.xtend
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/XtendUiModule.java

Change-Id: Ia6bba6f694ece0d3b42cc93cfca6602abadeda10

[#145] Adapted implementation to use moved/new interface.

---

org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/XtendResourceSetBasedResourceDescriptionsTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/batch/TestBatchCompiler.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/conversion/JavaIDValueConverterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/imports/AbstractRewritableImportSectionTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/javaconverter/JavaFileConverterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/lib/PathTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/JavaIoFileSystemTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/declaration/ConstantExpressionsInterpreterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/ReorderedFeatureCallArgumentsTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/ReorderedVarArgFeatureCallArgumentsTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/StandardFeatureCallArgumentsTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/VarArgFeatureCallArgumentsTest.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/compiler/XtendGenerator.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/ASTParserFactory.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/AbstractFileSystemSupport.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/AnnotationProcessor.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/ConstantExpressionsInterpreter.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/FilteringClassLoader.java
org.eclipse.xtend.ide.swtbot.tests/swtbot/xtend-gen/org/eclipse/xtend/ide/tests/SwtBotProjectHelper.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/document/DocumentRewriterTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/editor/XbaseEditorOpenClassFileTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/EclipseFileSystemTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/JavaIoFileSystemTest.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/autoedit/RichStringPartionIndentationStrategy.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/hyperlinking/ConsoleHyperlinking.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/hyperlinking/XtendFileHyperlink.java

[420984] Compiler optimization: Suppress unused exception variable

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target

build against latest photon
https://github.com/eclipse/xtext-eclipse/issues/530
https://github.com/eclipse/xtext-eclipse/issues/539

build against latest photon

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/builder/BuildAffectionTest.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/builder/WorkspaceScenariosTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/builder/BuildAffectionTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/builder/WorkspaceScenariosTest.java

fixed deprecated code

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/compiler/batch/Main.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/AnnotationProcessor.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/AnnotationProcessor.java

[#358] shutdown executor service after compile

[#358] shutdown executor service after compile

---

releng/org.eclipse.xtend.maven.parent/pom.xml

set lower guava bound to < 22

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBugTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBugTest.java

fixed broken tests after switch to guava 21

fixed broken tests after switch to guava 21

---

gradle/upstream-repositories.gradle
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBugProtectedVisibilityTest.xtend
org.eclipse.xtend.core.tests/testdata/testdata/ClazzWithProtectedMember.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBugProtectedVisibilityTest.java

Tests for https://github.com/eclipse/xtext-extras/issues/229

---

releng/org.eclipse.xtend.maven.parent/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

update to tycho 1.1.0 https://github.com/eclipse/xtext/issues/1172

update to tycho 1.1.0

---

Jenkinsfile

added hint on target platform to label

---

org.eclipse.xtend.ide.swtbot.tests/META-INF/MANIFEST.MF

use junit 4.12

---

org.eclipse.xtend.core/META-INF/MANIFEST.MF

maintained x-friends https://github.com/eclipse/xtext/issues/1173

maintained x-friends

---

org.eclipse.xtend.ide.swtbot.tests/pom.xml

[#375] fixed broken xtend maven plugin config

[#375] fixed broken xtend maven plugin config

---

org.eclipse.xtend.maven.plugin/pom.xml
releng/org.eclipse.xtend.tycho.tests.parent/pom.xml

no MaxPermSize

---

org.eclipse.xtend.ide.swtbot.tests/pom.xml

[#379] Fixed broken Tests

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/ModifierValidator.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendConfigurableIssueCodes.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/validator/preferences/XtendValidatorConfigurationBlock.java

[#384] made severity of redundant modifier configurable

[#384] made severity of redundant modifier configurable

---

org.eclipse.xtend.maven.plugin/.classpath

fixed m2e settings for photon
https://github.com/eclipse/xtext/issues/1180

fixed m2e settings for photon

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/build/XtendIncrementalBuilderTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/NestedClassValidationTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/build/XtendIncrementalBuilderTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/NestedClassValidationTest.java

Fixed broken unused local var tests

---

org.eclipse.xtend.core.tests.java8/src/org/eclipse/xtend/core/tests/java8/javaconverter/Java8ConverterTest.xtend
org.eclipse.xtend.core.tests.java8/xtend-gen/org/eclipse/xtend/core/tests/java8/javaconverter/Java8ConverterTest.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/javaconverter/JavaConverterTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/javaconverter/JavaConverterTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/javaconverter/JavaASTFlattener.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/JavaASTFlattener.java

[411549] J2X Support for try multi catch

---

org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/AbstractXtendCompilerMojo.java

Signed-off-by: Michael Keppler <Michael.Keppler@gmx.de>

Fix typo in log message

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/formatting/preferences/FormatterModifyDialog.java

[#412] Removed @Override to restore eclipse photon compatibility.

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/typesystem/CommonSuperTypeTest.xtend
org.eclipse.xtend.core.tests/testdata/bug495314/ClassA.java
org.eclipse.xtend.core.tests/testdata/bug495314/ClassB.java
org.eclipse.xtend.core.tests/testdata/bug495314/ClassC.java
org.eclipse.xtend.core.tests/testdata/bug495314/ClassD.java
org.eclipse.xtend.core.tests/testdata/bug495314/ClassE.java
org.eclipse.xtend.core.tests/testdata/bug495314/ParameterizedAbstractType.java
org.eclipse.xtend.core.tests/testdata/bug495314/ParameterizedAbstractType2.java
org.eclipse.xtend.core.tests/testdata/gh158/AbstractForm.java
org.eclipse.xtend.core.tests/testdata/gh158/AbstractP.java
org.eclipse.xtend.core.tests/testdata/gh158/Form1.java
org.eclipse.xtend.core.tests/testdata/gh158/Form2.java
org.eclipse.xtend.core.tests/testdata/gh158/P1.java
org.eclipse.xtend.core.tests/testdata/gh158/P2.java
org.eclipse.xtend.core.tests/testdata/gh158/View.java
org.eclipse.xtend.core.tests/testdata/gh158/View1.java
org.eclipse.xtend.core.tests/testdata/gh158/View2.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/CommonSuperTypeTest.java

Tests are here. Impl is in extras.

[495314] Fixed stackoverflow in type computation

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java

[eclipse/xtext-xtend#408] Added More Tests

[eclipse/xtext-xtend#408] Added More Tests

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java

[#408] Simplify QuickfixTest test case by eliminating unused imports.

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java

[#415] Add test cases reproducing the issue (some of them are ignored)

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java

[#415] Activate QuickfixTest that has been deactivated by accident.

---

org.eclipse.xtend.doc/gen_eclipse_help_xtend.launch

fixed broken launch config

---

org.eclipse.xtend.doc/contents/102_moviesexample.html
org.eclipse.xtend.doc/contents/203_xtend_expressions.html
org.eclipse.xtend.doc/contents/toc.xml

fixed the the

---

gradle/versions.gradle
org.eclipse.xtend.caliper.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.core.tests.java8/META-INF/MANIFEST.MF
org.eclipse.xtend.core.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.core/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.maven.parent/pom.xml
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-luna.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target

use asm 6.1.1
use jdt oxygen
adjusted pipelines

Java 10 Integration

---

org.eclipse.xtend.ide/plugin.xml

[#440] Enable run action for JUnit 5 tests

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-luna.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target

[eclipse/xtext#1198] Update Orbit URL to Photon M7

---

org.eclipse.xtend.examples/projects/xtend-euler/.settings/org.eclipse.jdt.core.prefs

fixed broken example

---

org.eclipse.xtend.doc/contents/203_xtend_expressions.html

[#324] regenerated docs

---

gradle/bootstrap-setup.gradle
gradle/versions.gradle
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1178] bootstrap against 2.14

[eclipse/xtext#1178] bootstrap against 2.14

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/autoedit/AutoEditTest.java

Bundle multiple actions that are performed to set up projects for
testing in the workspace in an IWorkspaceRunnable
Test with AutoEditInFirstMethodTest showed improvement from 61s to 50s on my local machine.

[#460] Improve UI test performance

---

releng/org.eclipse.xtend.maven.parent/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1225] Update to Tycho 1.2.0

---

gradle/developers.gradle
releng/org.eclipse.xtend.maven.parent/pom.xml

Signed-off-by: Lorenzo Bettini <lorenzo.bettini@gmail.com>

Just updated my email and organization in parent pom

---

org.eclipse.xtend.maven.android.archetype/pom.xml
org.eclipse.xtend.maven.archetype/pom.xml
org.eclipse.xtend.maven.plugin/pom.xml

Signed-off-by: Lorenzo Bettini <lorenzo.bettini@gmail.com>

left a comment on why groupId and version must be repeated

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-luna.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target

updated orbit to photon release

---

gradle/developers.gradle
releng/org.eclipse.xtend.maven.parent/pom.xml

Add contact data in parent pom and gradle files.

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/XtendFormatterBugTests.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendFormatterBugTests.java

[eclipse/xtext-core#527][eclipse/xtext-xtend#478] added more tests

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target

use photon release update site

---

releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1231] added workaround

[eclipse/xtext#1231] added workaround

---

gradle/bootstrap-setup.gradle
gradle/versions.gradle
org.eclipse.xtend.core/build.gradle
releng/org.eclipse.xtend.maven.parent/pom.xml

[eclipse/xtext#1231] fixed jdt and platform versions

[eclipse/xtext#1231] fixed jdt and platform versions

---

org.eclipse.xtend.core/build.gradle

[eclipse/xtext#1231] more precise exclusions

[eclipse/xtext#1231] more precise exclusions

---

Jenkinsfile
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1228] Build Against Post Photon Platform and JDT

[eclipse/xtext#1228] Build Against Post Photon Platform and JDT

---

org.eclipse.xtend.maven.plugin/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtend.standalone/.settings/org.eclipse.jdt.core.prefs

compile with java 8

---

org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/XtendFormatter.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/labeling/XtendLabelProvider.java

regenerated against latest xtend

---

org.eclipse.xtend.core/.classpath
org.eclipse.xtend.ide.common/.classpath

[eclipse/xtext#1247] including attribute added for classpathentry

---

Jenkinsfile

[eclipse/xtext-eclipse#747] archive junit logs

[eclipse/xtext-eclipse#747] archive junit logs

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/hierarchy/ShowHierarchyTest.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/WorkbenchTestHelper.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/editor/XbaseEditorOpenClassFileTest.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/editor/RichStringAwareSourceViewer.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/editor/XtendEditorAdapterFactory.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/view/DerivedSourceView.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/wizards/FieldInitializerUtil.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/javaconverter/EclipseASTParserFactory.java
org.eclipse.xtend.performance.tests/src/org/eclipse/xtend/performance/tests/PerformanceTestProjectSetup.java

fixed warnings after move to oxygen

---

org.eclipse.xtend.doc/contents/204_activeannotations.html

[#458] regenerated docs

---

releng/org.eclipse.xtend.maven.parent/pom.xml

[#534] Upgrade maven-javadoc-plugin version

---

releng/org.eclipse.xtend.tycho.parent/pom.xml

better workaround for signing issue

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/XtendRenameRefactoringTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/refactoring/XtendRenameRefactoringTest.java

[#164] Add a test case reproducing the issue (currently ignored).

---

gradle/versions.gradle
org.eclipse.xtend.caliper.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.core.tests.java8/META-INF/MANIFEST.MF
org.eclipse.xtend.core.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.core/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.maven.parent/pom.xml
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target

[eclipse/xtext#1266] Update to ASM 6.2

[eclipse/xtext#1266] Update to ASM 6.2

---

org.eclipse.xtend.maven.archetype/pom.xml

[#140] ignored tests again

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/WorkbenchTestHelper.java

reverted changes to MergableManifest

---

Jenkinsfile
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1273] build against 2018-09 and 2018-12

[eclipse/xtext#1273] build against 2018-09 and 2018-12

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/MoreActiveAnnotationsTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/MoreActiveAnnotationsTest.java

[#554] Adapt test expectations 'static final' instead of 'final static'.

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target

[eclipse/xtext#1298] updated to 2018-09/4.9 final

[eclipse/xtext#1298] updated to 2018-09/4.9 final

---

org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/EmfModelsTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/batch/TestBatchCompiler.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/findReferences/Declarators.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/XtendFormatterPreferenceKeys.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/ActiveAnnotationContextProvider.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/AnnotationProcessor.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/FilteringClassLoader.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/ProcessorInstanceForJvmTypeProvider.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/resource/XtendResourceDescription.java
org.eclipse.xtend.ide.common/xtend-gen/org/eclipse/xtend/ide/common/highlighting/XtendAntlrTokenToAttributeIdMapper.java
org.eclipse.xtend.ide.common/xtend-gen/org/eclipse/xtend/ide/common/highlighting/XtendHighlightingStyles.java
org.eclipse.xtend.ide.swtbot.tests/swtbot/xtend-gen/org/eclipse/xtend/ide/tests/SwtBotProjectHelper.java
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/builder/JavaEditorExtension.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/builder/KeepLocalHistoryTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/codebuilder/AbstractBuilderTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/contentassist/Bug462915Test.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/editor/DirtyStateEditorSupportTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/editor/DirtyStateEditorValidationTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/editor/XbaseEditorOpenClassFileTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/highlighting/HighlightingReconcilerTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/builder/UIResourceChangeRegistry.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/codebuilder/AbstractExecutableBuilder.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/macro/JdtBasedProcessorProvider.java

Order of static & final modifiers changed
(eclipse/xtext-xtend#554)

[eclipse/xtext#1272] Compile with Xtend 2.15

---

org.eclipse.xtend.examples/projects/xtend-examples/src/example2/BasicExpressions.xtend

Xtend-examples: Fix broken link to the Xtend operators documentation.

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/compiler/batch/XtendBatchCompiler.java
org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/AbstractXtendCompilerMojo.java

[#582] Evaluate bootclasspath only for Java <= 1.8

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target

updated to orbit 2018-12-M1

---

gradle/versions.gradle
maven-pom.xml
org.eclipse.xtend.maven.android.archetype/pom.xml
org.eclipse.xtend.maven.archetype/pom.xml
org.eclipse.xtend.maven.plugin/pom.xml

Signed-off-by: Prajwal Gowda <pgowda@itemis.de>

[release] version 2.16.0.M1

---

org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/ClassFileDebugSourceExtractor.java
org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/ClassFileDebugInfoExtractor.java

use asm 7 experimental towards java 11

use asm 7 experimental towards java 11

---

gradle/versions.gradle
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1321] bootstrap against 2.16.0.M1

[eclipse/xtext#1321] bootstrap against 2.16.0.M1

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/WorkbenchTestHelper.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/validation/AccessRestrictionInWorkspaceTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/validation/AccessRestrictionInWorkspaceTest.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/buildpath/XtendLibClasspathAdder.java

eclipse/xtext-core#864: Use only MergeableManifest2 internally.

---

gradle/versions.gradle
org.eclipse.xtend.caliper.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.core.tests.java8/META-INF/MANIFEST.MF
org.eclipse.xtend.core.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.core/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF
org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/ClassFileDebugSourceExtractor.java
org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/ClassFileDebugInfoExtractor.java
releng/org.eclipse.xtend.maven.parent/pom.xml
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target

[eclipse/xtext#1325] switch to ASM 7

[eclipse/xtext#1325] switch to ASM 7

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/hyperlinking/JavaDocHyperlinkingTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/hyperlinking/JavaDocHyperlinkingTest.java

Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=431101

[#372] Implement JavaDocHyperlinkingTest test cases.

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/AnnotationWithNestedAnnotationsProcessor.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/AnnotationWithNestedAnnotationsProcessorTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/AnnotationWithNestedAnnotations.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/AnnotationWithNestedAnnotationsProcessor.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/AnnotationWithNestedAnnotationsProcessorTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/declaration/CompilationUnitImpl.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/declaration/CompilationUnitImpl.java

[eclipse/xtext-xtend#624] fixed nested annotation lists

[eclipse/xtext-xtend#624] fixed nested annotation lists

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/hover/XtendHoverInEditorTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/hover/XtendHoverInEditorTest.java

[#372] Implement XtendHoverInEditorTest javadoc hovering test cases.

---

Jenkinsfile
releng/org.eclipse.xtend.tycho.tests.parent/pluginCustomization.ini
releng/org.eclipse.xtend.tycho.tests.parent/pom.xml

When OK changes to target def and Jenkinsfile have to be reverted

[540316] Enable parallel XtextBuilder execution

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/compiler/batch/XtendBatchCompiler.java
org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/AbstractXtendCompilerMojo.java

Also fixed typo in the message.

[#582] Print warn message only when bootclasspath is not empty

---

Jenkinsfile
org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/MavenVerifierUtil.java
org.eclipse.xtend.maven.plugin/src/test/resources/settings.xml

[#608] fixed settings.xml problem on ci.eclipse.org

---

org.eclipse.xtend.examples/pom.xml

[eclipse/xtext-eclipse#907] repaired cleaning of example projects

[eclipse/xtext-eclipse#907] repaired cleaning of example projects

---

org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/MavenVerifierUtil.java

[#650] enabled mvn debug and -U for tests

---

Jenkinsfile
org.eclipse.xtend.maven.plugin/pom.xml
org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/MavenVerifierUtil.java
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml

[#652] fixed build

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target

switched to orbit 2019-03

---

org.eclipse.xtend.m2e/src/org/eclipse/xtend/m2e/XtendProjectConfigurator.java

[#647] fixed deprecations in xtend m2e integration

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/ContentAssistTest.java

[#662] fixed failing test

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/compiler/JavaVersionSettingTest.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/Bug457681Test.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/compiler/JavaVersionSettingTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/Bug457681Test.java

[#557] fixed failing tests reg. missing target platform

[#557] fixed failing tests reg. missing target platform

---

gradle/versions.gradle
releng/org.eclipse.xtend.tycho.parent/pom.xml

Signed-off-by: Prajwal Gowda <pgowda@itemis.de>
@cdietrich  could you please review it

bootstraping version to 2.16.0

---

Jenkinsfile
org.eclipse.xtend.ide.swtbot.tests/pom.xml

#669 Archive screenshots and clean them before build.

---

releng/org.eclipse.xtend.maven.parent/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml
releng/org.eclipse.xtend.tycho.tests.parent/pom.xml

[eclipse/xtext#1322] switched to tycho 1.3.0

[eclipse/xtext#1322] switched to tycho 1.3.0

---

gradle/eclipse-project-layout.gradle
org.eclipse.xtend.ide/about.mappings
org.eclipse.xtend.ide/about.properties
org.eclipse.xtend.ide/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1371] fixed filtering of about.mappings

[eclipse/xtext#1371] fixed filtering of about.mappings

---

Jenkinsfile
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1363] prepare build against 2019-03

[eclipse/xtext#1363] prepare build against 2019-03

---

org.eclipse.xtend.caliper.tests/src/org/eclipse/xtend/caliper/tests/RuntimeTestSetup.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/RuntimeTestSetup.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/ActiveAnnotationsRuntimeTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/ActiveAnnotationsRuntimeTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/CachingResourceValidatorImpl.xtend
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/IssueCodes.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendConfigurableIssueCodes.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/validation/CachingResourceValidatorImpl.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/RuntimeTestSetup.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/validator/XtendUIValidator.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/validator/preferences/XtendValidatorConfigurationBlock.java

Fixing typos into the IssueCodes class.

---

gradle/developers.gradle
releng/org.eclipse.xtend.maven.parent/pom.xml

[https://github.com/eclipse/xtext/issues/1330] Update developers section

---

gradle/versions.gradle
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1382] Bootstrap against 2.17.0.M1

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1372] Use 2019-03 in target platforms

[eclipse/xtext#1372] Use 2019-03 in target platforms

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/AnnotationTestingTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/batch/TestBatchCompiler.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/javaconverter/JavaFileConverterTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/ActiveAnnotationsRuntimeTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/AnnotationTestingTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/batch/TestBatchCompiler.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/javaconverter/JavaFileConverterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/ActiveAnnotationsRuntimeTest.java
org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/MavenVerifierUtil.java

fixed guava deprecations

---

org.eclipse.xtend.core.tests.java8/.classpath
org.eclipse.xtend.core.tests/.classpath
org.eclipse.xtend.core.tests/org.eclipse.xtend.core.tests.smoke-suites.launch
org.eclipse.xtend.core/.classpath
org.eclipse.xtend.ide.common/.classpath

Changes done by Buildship 3.0.1.v20181217-1554

[eclipse/xtext#1274] Updated .classpath by Gradle

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/compiler/batch/XtendBatchCompiler.java

fixed wrong see link in javadoc

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/ValidationIssue719QuickFixTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/ValidationIssue719QuickFixTest.java

Corrected remarks of @miklossy
Signed-off-by: Eva Poell <epoell@itemis.com>

[#719] Corrected Typos in Issuemessage and AnnotationTest.

---

org.eclipse.xtend.core/src-gen/org/eclipse/xtend/core/serializer/AbstractXtendSyntacticSequencer.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/serializer/XtendSyntacticSequencer.java

[544435] regenerated xtend

---

Jenkinsfile
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1412] build against 2019-03 release

[eclipse/xtext#1412] build against 2019-03 release

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/javaconverter/PasteJavaCodeHandler.java

[#753] prevent pasting on non editable editors

[#753] prevent pasting on non editable editors

---

gradle/upstream-repositories.gradle
releng/org.eclipse.xtend.maven.parent/pom.xml

replaced tf jenkins with ci.eclipse.org/xtext for lsp4j

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/JavaRefactoringIntegrationTest.java

#767 Avoid try/finally to avoid exception swallow and fix cleanup.

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/JavaRefactoringIntegrationTest.java

Simplify test code a bit, make it more readable.

#767 Clear every file from source folder on cleanup.

---

releng/org.eclipse.xtend.maven.parent/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1422] update to tycho 1.4.0

[eclipse/xtext#1422] update to tycho 1.4.0

---

CBI.Jenkinsfile

[eclipse/xtext#1430] added missing tp to CBI

[eclipse/xtext#1430] added missing tp to CBI

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/hierarchy/ShowHierarchyTest.java

[#780] fixed NPE in ShowHierarchyTest

[#780] fixed NPE in ShowHierarchyTest

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/buildpath/JavaClasspathTest.java

[#777] Make JavaClasspathTest compatible to latest

[#777] Make JavaClasspathTest compatible to latest

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/quickfix/XtendQuickfixProvider.java

[#744] Quickfix for wrong file name
replaces https://github.com/eclipse/xtext-xtend/pull/747

[#744] Quickfix for wrong file name

---

org.eclipse.xtend.doc/contents/203_xtend_expressions.html
org.eclipse.xtend.doc/contents/toc.xml

regenerated docs from website

---

gradle/versions.gradle
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/EmfModelsTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/imports/AbstractRewritableImportSectionTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/javaconverter/JavaConverterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/lib/PathTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/declaration/ConstantExpressionsInterpreterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/declaration/DeclarationsTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/resource/ResourceStorageTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/ReorderedFeatureCallArgumentsTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/ReorderedVarArgFeatureCallArgumentsTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/StandardFeatureCallArgumentsTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/VarArgFeatureCallArgumentsTest.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/JavaASTFlattener.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/AbstractFileSystemSupport.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/declaration/ProblemSupportImpl.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/editor/XbaseEditorOpenClassFileTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/AbstractReusableActiveAnnotationTests.java
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1437] Bootstrap against 2.18.0.M2

[eclipse/xtext#1437] Bootstrap against 2.18.0.M2

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/AccessorsCompilerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerTest.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerTestHelper.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/DelegateCompilerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/EqualsHashCodeCompilerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/PropertyCompilerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/ToStringCompilerTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/AccessorsCompilerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/DelegateCompilerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/EqualsHashCodeCompilerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/PropertyCompilerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/ToStringCompilerTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/ProcessorInstanceForJvmTypeProvider.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/ProcessorInstanceForJvmTypeProvider.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/macro/JdtBasedProcessorProvider.xtend
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/macro/JdtBasedProcessorProvider.java

fixed deprecations with java 11

fixed deprecations with java 11

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/AbstractXtendTestCase.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/ConfiguredCompilerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/batch/TestBatchCompiler.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/imports/ImportsCollectorTests.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/performance/XtendFileGenerator.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/typesystem/BoundTypeArgumentMergerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/typesystem/CommonSuperTypeTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/ConfiguredCompilerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/batch/TestBatchCompiler.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/imports/ImportsCollectorTests.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/performance/XtendFileGenerator.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/BoundTypeArgumentMergerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/CommonSuperTypeTest.java

[#800] fixed tests on java 11

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/AbstractXtendUITestCase.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/hover/JvmAnnotationReferencePrinterTest.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/ActiveAnnotationsProcessingInIDETest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/hover/JvmAnnotationReferencePrinterTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/ActiveAnnotationsProcessingInIDETest.java

[#800] fixed annotation tests with j11

[#800] fixed annotation tests with j11

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/MutableElementsConditionsTestCase.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/CheckMutableMethodDeclarationProcessor.java

fixed ambiguity warning

---

org.eclipse.xtend.core.tests.java8/src/org/eclipse/xtend/core/tests/java8/compiler/CompilerBug406425Test.xtend
org.eclipse.xtend.core.tests.java8/src/org/eclipse/xtend/core/tests/java8/compiler/CompilerBug457539Test.xtend
org.eclipse.xtend.core.tests.java8/src/org/eclipse/xtend/core/tests/java8/compiler/StringBuilderLike.java
org.eclipse.xtend.core.tests.java8/xtend-gen/org/eclipse/xtend/core/tests/java8/compiler/CompilerBug406425Test.java
org.eclipse.xtend.core.tests.java8/xtend-gen/org/eclipse/xtend/core/tests/java8/compiler/CompilerBug457539Test.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBug406425Test.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBug457539Test.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/StringBuilderLike.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBug406425Test.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBug457539Test.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/compiler/RebuildAffectedResourcesTest.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/AbstractXbaseContentAssistTest.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/Bug435184Test.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/ContentAssistInElseBlockTest.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/ContentAssistInLambdaTest2.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/ContentAssistTest.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/DataContentAssistTest.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/hover/XtendHoverDocumentationProviderTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/compiler/RebuildAffectedResourcesTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/contentassist/Bug435184Test.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/contentassist/DataContentAssistTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/hover/XtendHoverDocumentationProviderTest.java

[#800] made more tests runnable on java 8 and java 11

[#800] made more tests runnable on java 8 and java 11

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/editor/XbaseEditorOpenClassFileTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/editor/XbaseEditorOpenClassFileTest.java

Fixed resource leak in tests.
Fixes #813

Fixed resource leak in tests.

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

fixed wrong usage of http

---

Jenkinsfile

harmonized labels

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/document/DocumentRewriterTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/document/DocumentRewriterTest.java

Fixed another test failing on Windows

Fixed another test failing on Windows

---

org.eclipse.xtend.doc/contents/204_activeannotations.html

regenerated docs for 2.18

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target

[eclipse/xtext#1475] build against orbit 2019-09

[eclipse/xtext#1475] build against orbit 2019-09

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/folding/XtendFoldingRegionProviderTest.java

- Eliminate duplicated code to improve the readability of the test
cases.

Refactoring the XtendFoldingRegionProviderTest class.

---

CBI.Jenkinsfile
Jenkinsfile
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1475] prepared target platform for 2019-09

[eclipse/xtext#1475] prepared target platform for 2019-09

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1485] update to mwe 2.11

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/linking/LinkingErrorTest.java

[eclipse/xtext-extras#445] Test cases

 [eclipse/xtext-extras#445] Test cases

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/AbstractXtendTestCase.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/typesystem/ActualTypeArgumentMergeTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/typesystem/BoundTypeArgumentMergerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/typesystem/CommonSuperTypeTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/typesystem/SuperTypeTests.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/ActualTypeArgumentMergeTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/AllSuperTypesTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/BoundTypeArgumentMergerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/CommonSuperTypeTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/SuperTypesTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/javaconverter/ASTParserFactory.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/ASTParserFactory.java

made tests runnable with java 12

made tests runnable with java 12

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/javaconverter/ASTParserFactory.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/ASTParserFactory.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/javaconverter/PasteJavaCodeHandler.java
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target

[eclipse/xtext-xtend#818] Add classgraph to target platform

[eclipse/xtext-xtend#818] Add classgraph to target platform

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerTestHelper.java

performance opt. longrunning tests

performance opt. longrunning tests

---

CBI.Jenkinsfile

[eclipse/xtext#1491] harmoized target_platform variable in Jenkinsfile

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/builder/XtendBuilderParticipantTest.java

[eclipse/xtext-extras#343] Test case

[eclipse/xtext-extras#343] Test case

---

Jenkinsfile

[eclipse/xtext#1384] Convert Jenkinsfile to declarative pipeline

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/JavaRefactoringIntegrationTest.java

[#767] ignored JavaRefactoringIntegrationTest on Oxygen

[#767] ignored JavaRefactoringIntegrationTest on Oxygen

---

CBI.Jenkinsfile

[eclipse/xtext#1465] Use declarative JUnit step

---

org.eclipse.xtend.core.tests.java8/src/org/eclipse/xtend/core/tests/java8/compiler/CompilerBug462845Test.xtend
org.eclipse.xtend.core.tests.java8/src/org/eclipse/xtend/core/tests/java8/compiler/TryWithResourcesTestJava8.xtend
org.eclipse.xtend.core.tests.java8/xtend-gen/org/eclipse/xtend/core/tests/java8/compiler/CompilerBug462845Test.java
org.eclipse.xtend.core.tests.java8/xtend-gen/org/eclipse/xtend/core/tests/java8/compiler/TryWithResourcesTestJava8.java

[#831] adjusted tests to fixed compilation

[#831] adjusted tests to fixed compilation

---

org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/AbstractReusableActiveAnnotationTests.java
org.eclipse.xtend.examples/projects/xtend-examples/xtend-gen/example6/Movies.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/contentassist/JavaDocContentAssistTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/hyperlinking/JavaDocHyperlinkingTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/AbstractReusableActiveAnnotationTests.java

regenerate with latest xtend

---

releng/org.eclipse.xtend.maven.parent/pom.xml

bumped some maven plugins

---

gradle/upstream-repositories.gradle
releng/org.eclipse.xtend.maven.parent/pom.xml

Signed-off-by: Nico Prediger <mail@nicoprediger.de>

[eclipse/xtext#1507] Adjust lsp4j upstream URL / Use env.JENKINS_URL

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/ActiveAnnotationContext.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/ActiveAnnotationContextProvider.java

[#886] Log exceptions from annotation processors

[#886] Log exceptions from annotation processors

---

org.eclipse.xtend.core.tests/xtend.core.tests.fast.launch
org.eclipse.xtend.core.tests/xtend.core.tests.slow.launch
org.eclipse.xtend.ide.tests/xtend.ide.tests.fast (xtend).launch
org.eclipse.xtend.ide.tests/xtend.ide.tests.fast-quarantine.launch
org.eclipse.xtend.ide.tests/xtend.ide.tests.fast.launch
org.eclipse.xtend.ide.tests/xtend.ide.tests.slow (xtend).launch
org.eclipse.xtend.ide.tests/xtend.ide.tests.slow.launch
org.eclipse.xtend.performance.tests/performance.tests.launch

removed ancient relics from launch configs

removed ancient relics from launch configs

---

releng/org.eclipse.xtend.maven.parent/pom.xml

bumped org.eclipse.xtext.maven.parent/pom.xml

---

CBI.Jenkinsfile
Jenkinsfile

[eclipse/xtext#1513] Add nightly master-trigger to replace trigger job
Signed-off-by: Nico Prediger <mail@nicoprediger.de>

[eclipse/xtext#1513] Add nightly master-trigger to replace trigger job

---

releng/org.eclipse.xtend.tycho.parent/pom.xml

preserve parameter names during compilation with tycho

---

org.eclipse.xtend.doc/contents/204_activeannotations.html

regenerated help pages

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

bootstrap against m3

---

gradle/wrapper/gradle-wrapper.properties
gradlew
org.eclipse.xtend.core.tests.java8/.classpath
org.eclipse.xtend.core.tests/.classpath

[eclipse/xtext#1520] update to gradle 5.6.1

[eclipse/xtext#1520] update to gradle 5.6.1

---

org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/XtendInstallDebugInfoMojoIT.java
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml

set maven compiler version to 8

set maven compiler version to 8

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1538] use 4.14 I-Builds repo in latest

[eclipse/xtext#1538] use 4.14 I-Builds repo in latest

---

org.eclipse.xtend.maven.archetype/pom.xml
org.eclipse.xtend.maven.plugin/pom.xml

[eclipse/xtext#1552] removed duplicate groupId & version

[eclipse/xtext#1552] removed duplicate groupId & version

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/AbstractXtendTestCase.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/javaconverter/ASTParserFactory.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/ASTParserFactory.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/AbstractXtendUITestCase.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/AbstractXbaseContentAssistTest.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/ContentAssistInElseBlockTest.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/ContentAssistInLambdaTest2.java

Made J2X runnable with Java 13 as underlaying JDK + Fix some failing 

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target

[eclipse/xtext#1538] use orbit 2019-12

[eclipse/xtext#1538] use orbit 2019-12

---

README.md

updated readme regarding gradle publish

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/labeling/XtendDescriptionLabelProvider.java

[https://github.com/eclipse/xtext/issues/1556]

---

releng/org.eclipse.xtend.maven.parent/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1553] update to tycho 1.5.0

[eclipse/xtext#1553] update to tycho 1.5.0

---

org.eclipse.xtend.core.tests.java8/META-INF/MANIFEST.MF
org.eclipse.xtend.core.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.core/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target

[eclipse/xtext#1567] Upgrade to asm 7.2

[eclipse/xtext#1567] Upgrade to asm 7.2

---

gradle/eclipse-project-layout.gradle
org.eclipse.xtend.core.tests.java8/.project
org.eclipse.xtend.core.tests/.project
org.eclipse.xtend.core/.project
org.eclipse.xtend.ide.common/.project

[eclipse/xtext#1573] Ensure that all plugins do have a ManifestBuilder

[eclipse/xtext#1573] Ensure that all plugins do have a ManifestBuilder

---

releng/org.eclipse.xtend.maven.parent/pom.xml

bumped maven-source-plugin

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.20.0.M2

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.tycho.parent/pom.xml

removed traces to xpand and old generator

removed traces to xpand and old generator

---

org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/XImportSectionValidationTest.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/resource/XtendResourceDescriptionManager.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTestBuilder.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/autoedit/RichStringPartionIndentationStrategy.java

regenerated with latest xbase.lib

regenerated with latest xbase.lib

---

gradle/manifest-gen.gradle
org.eclipse.xtend.core/META-INF/MANIFEST.MF
org.eclipse.xtend.ide.common/META-INF/MANIFEST.MF
org.eclipse.xtend.ide/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1504] added Eclipse-SourceReferences to manifests

[eclipse/xtext#1504] added Eclipse-SourceReferences to manifests

---

org.eclipse.xtend.core/META-INF/MANIFEST.MF
org.eclipse.xtend.core/build.properties

moved mwe deps to build.properties

moved mwe deps to build.properties

---

org.eclipse.xtend.maven.archetype/.classpath
org.eclipse.xtend.maven.plugin/.classpath
org.eclipse.xtend.maven.plugin/.gitignore

[eclipse/xtext#1573] Do not share output folders between mvn and Eclipse

[eclipse/xtext#1573] Do not share output folders mvn vs Eclipse

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1609] update to mwe 2.11.1

[eclipse/xtext#1609] update to mwe 2.11.1

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.20.0.M3

---

Jenkinsfile
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target
releng/org.eclipse.xtend.target/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1603] create target for r201912

[eclipse/xtext#1603] create target for r201912

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.20.0

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/WorkbenchTestHelper.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/buildpath/XtendLibClasspathAdderTest.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/compiler/Bug456868Test.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/compiler/UnicodeEscapeTest.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/ContentAssistTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/compiler/Bug456868Test.java
org.eclipse.xtend.performance.tests/src/org/eclipse/xtend/performance/tests/PerformanceTestProjectSetup.java

change default bree/complicance

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/highlighting/HighlightingReconcilerTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/highlighting/HighlightingReconcilerTest.java

[#880] ignored flaky HighlightingReconcilerTest

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/declaration/CompilationUnitImpl.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/declaration/CompilationUnitImpl.java

[eclipse/xtext-eclipse#1228] Impl getDocComment to use it in wizard.

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1604] updated to 2020-03 simrel update site

[eclipse/xtext#1604] updated to 2020-03 simrel update site

---

releng/org.eclipse.xtend.maven.parent/pom.xml

updated maven-source-plugin

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target

[eclipse/xtext#1605] update orbit to 2020-03

[eclipse/xtext#1605] update orbit to 2020-03

---

org.eclipse.xtend.ide/plugin.xml

[#988] performance optimization console hyperlinking regex

[#988] performance optimization console hyperlinking regex

---

org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/AnnotationWithNestedAnnotations.java
org.eclipse.xtend.examples/projects/xtend-annotation-examples-client/xtend-gen/extract/ExtractExampleInterface.java
org.eclipse.xtend.ide.common/xtend-gen/org/eclipse/xtend/ide/common/highlighting/XtendHighlightingStyles.java
org.eclipse.xtend.ide.common/xtend-gen/org/eclipse/xtend/ide/common/outline/IXtendOutlineContext.java
org.eclipse.xtend.ide.common/xtend-gen/org/eclipse/xtend/ide/common/outline/IXtendOutlineNodeBuilder.java
org.eclipse.xtend.ide.common/xtend-gen/org/eclipse/xtend/ide/common/outline/IXtendOutlineTreeBuilder.java

[eclipse/xtext#1642] regenerated xtend code with latest xtend

[eclipse/xtext#1642] regenerated xtend code with latest xtend

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.21.0.M1

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/javaconverter/JavaConverterTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/javaconverter/JavaConverterTest.java

[eclipse/xtext#1455] Fix line endings for JavaConverterTest.

---

releng/org.eclipse.xtend.maven.parent/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1643] update to tycho 1.6.0

[eclipse/xtext#1643] update to tycho 1.6.0

---

releng/org.eclipse.xtend.tycho.tests.parent/pom.xml

removed duplicate extra requirement

removed duplicate extra requirement

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target

use junit 4.12 explicitely

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.21.0.M2

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

test with MWE 2.11.2.M3

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.21.0.M3

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1673] udpate to MWE 2.11.2

[eclipse/xtext#1673] udpate to MWE 2.11.2

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/richstring/InitialIndentationWithCommentsTest.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/richstring/RichStringWithCommentCompilerTest.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/richstring/RichStringWithCommentProcessorTest.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/richstring/RichStringWithCommentValidationTest.java
org.eclipse.xtend.core.tests/suites/org/eclipse/xtend/core/tests/linking/LinkingSuite.java

fixed unused imports

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/AnnotationCompilerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/XtendCompilerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/AnnotationPropertyTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/MutableElementsConditionsTestCase.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/AnnotationCompilerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/XtendCompilerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/AnnotationPropertyTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/MutableElementsConditionsTestCase.java

[eclipse/xtext-xtend#1014] adapted test expectations

[eclipse/xtext-xtend#1014] adapted test expectations

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.21.0

---

org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/MyAnnotation.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/batch/_TESTDATA_InternalClassAnnotation.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/AccessObjectAnn.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/Accessors.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/AddInterface.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/AddInterfaceWithDefault.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/ArtificialMethods.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/Bug446364.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/Bug456264.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/Bug464136.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/CheckMutableClassDeclaration.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/CheckMutableEnumerationTypeDeclaration.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/CheckMutableFieldDeclaration.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/CheckMutableInterfaceDeclaration.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/CheckMutableMethodDeclaration.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/CheckMutableParameterDeclaration.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/Get.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/Immutable.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/InferredTypeReferencesCheck.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/ToAnno.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/__GeneratedSourceModifingAnnotation.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/declaration/AddNestedTypes.java
org.eclipse.xtend.examples/projects/xtend-annotation-examples/xtend-gen/extract/Extract.java
org.eclipse.xtend.examples/projects/xtend-annotation-examples/xtend-gen/i18n/Externalized.java
org.eclipse.xtend.examples/projects/xtend-annotation-examples/xtend-gen/lazy/Lazy.java
org.eclipse.xtend.examples/projects/xtend-annotation-examples/xtend-gen/observables/Observable.java

regenerated xtend code

---

Jenkinsfile
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202003.target
releng/org.eclipse.xtend.target/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1686] prepared R2020-03 release target platform

[eclipse/xtext#1686] prepared R2020-03 release target platform

---

releng/org.eclipse.xtend.maven.parent/pom.xml

bumped maven javadoc plugin

---

org.eclipse.xtend.maven.plugin/pom.xml

excluded jdt.launching dependency
fixes #1013

excluded jdt.launching dependency

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/javaconverter/ASTParserFactory.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/ASTParserFactory.java
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/builder/SameClassNamesTest.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/AbstractXtendUITestCase.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/Bug427440Test.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/outline/JvmQuickOutlineTests.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/outline/QuickOutlineTests.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/builder/SameClassNamesTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/contentassist/Bug427440Test.java

made tests java 14 ready

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1685] use 2020-06 update site

[eclipse/xtext#1685] use 2020-06 update site

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202003.target

[eclipse/xtext#1682] update orbit to 2020-06

[eclipse/xtext#1682] update orbit to 2020-06

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.22.0.M1

---

org.eclipse.xtend.examples/pom.xml
releng/org.eclipse.xtend.maven.parent/pom.xml
releng/org.eclipse.xtend.p2-repository/pom.xml

[https://github.com/eclipse/xtext/issues/1742] Update

---

releng/org.eclipse.xtend.maven.parent/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[https://github.com/eclipse/xtext/issues/1732] Update to Tycho 1.7.0

---

org.eclipse.xtend.core.tests.java8/META-INF/MANIFEST.MF
org.eclipse.xtend.core.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.core/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF
org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/ClassFileDebugSourceExtractor.java
org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/ClassFileDebugInfoExtractor.java
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202003.target

[eclipse/xtext#1649] update to ASM 8.0

[eclipse/xtext#1649] update to ASM 8.0

---

org.eclipse.xtend.core/src-gen/org/eclipse/xtend/core/parser/antlr/internal/InternalXtend.g
org.eclipse.xtend.core/src-gen/org/eclipse/xtend/core/parser/antlr/internal/InternalXtendParser.java

[eclipse/xtext-core#1462] Regenerated languages

[eclipse/xtext-core#1462] Regenerated languages

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.22.0.M2

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1765] update to MWE 2.11.3.M3

[eclipse/xtext#1765] update to MWE 2.11.3.M3

---

org.eclipse.xtend.ide/plugin.xml
org.eclipse.xtend.ide/plugin.xml_gen

- Regenerate plugin.xml_gen.
- Merge plugin.xml_gen into plugin.xml.

Regenerate Xtend.

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1770] update to mwe 2.11.3 final

[eclipse/xtext#1770] update to mwe 2.11.3 final

---

org.eclipse.xtend.ide/plugin.xml_gen

Regenerate the org.eclipse.xtend.ide/plugin.xml_gen file.

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.22.0.M3

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.22.0

---

Jenkinsfile
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202006.target
releng/org.eclipse.xtend.target/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1785] created r202006 tp

[eclipse/xtext#1785] created r202006 tp

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1784]use 4.17 I-builds

[eclipse/xtext#1784]use 4.17 I-builds

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202003.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202006.target

[eclipse/xtext#1781] update orbit to 2020-09

[eclipse/xtext#1781] update orbit to 2020-09

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/declaration/JvmBasedDeclarations.xtend
org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/declaration/XtendBasedDeclarations.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/declaration/JvmMethodDeclarationImpl.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/declaration/XtendMethodDeclarationImpl.java

[#903] Allow to ask methods for their base method

[#903] Allow to ask methods for their base method

---

org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/declaration/UnknownType.java
org.eclipse.xtend.ide.common/xtend-gen/org/eclipse/xtend/ide/common/outline/DefaultXtendOutlineContext.java

regenerated with latest aa

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/Issue624Test.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/contentassist/Issue624Test.java

[eclipse/xtext-extras#624] Added tests

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.23.0.M1

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/EqualsWithNullMultiQuickfixTest.xtend
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/RemoveUnnecessaryModifiersMultiQuickfixTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/EqualsWithNullMultiQuickfixTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/RemoveUnnecessaryModifiersMultiQuickfixTest.java

multi quickfixes [2/3]
Added `EqualsWithNullMultiQuickfixTest` and
`RemoveUnnecessaryModifiersMultiQuickfixTest`
Signed-off-by: Aaron R Miller <aaron.miller@waweb.io>

[eclipse/xtext-xtend#1061] Provide ui test infrastructure for testing (WIP)

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/ValidationBug565585Test.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/ValidationBug565585Test.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java

Create Issue for current resource only
Fixes https://bugs.eclipse.org/bugs/show_bug.cgi?id=565585

Create Issue for current resource only

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.23.0.M2

---

Jenkinsfile

always archive ui test logs

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/javaconverter/ASTParserFactory.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/ASTParserFactory.java

made tests Java 15 ready

---

org.eclipse.xtend.ide.swtbot.tests/xtend.ide.tests.slow (SWTBot).launch
org.eclipse.xtend.ide.tests/xtend.ide.tests.fast-quarantine.launch
org.eclipse.xtend.ide.tests/xtend.ide.tests.fast.launch
org.eclipse.xtend.ide.tests/xtend.ide.tests.slow (xtend).launch
org.eclipse.xtend.ide.tests/xtend.ide.tests.slow.launch
org.eclipse.xtend.maven.archetype/.classpath
org.eclipse.xtend.performance.tests/performance.tests.launch

replaced outdated Java 6 refs with Java 8

replaced outdated Java 6 refs with Java 8

---

Jenkinsfile

run tests with java 11 (provisional fix)

run tests with java 11 (provisional fix)

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.23.0.M3

---

org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/symlinks/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml

fixed maven plugin symlink test (xtend.lib version)

fixed maven plugin symlink test (xtend.lib version)

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.23.0

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202006.target

fixed emf version in r202006

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1831] update latest to 4.18-I-builds

[eclipse/xtext#1831] update latest to 4.18-I-builds

---

Jenkinsfile
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202009.target
releng/org.eclipse.xtend.target/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1832] create r202009 target

[eclipse/xtext#1832] create r202009 target

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202003.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202006.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202009.target

[eclipse/xtext#1828] update orbit to 2020-12

[eclipse/xtext#1828] update orbit to 2020-12

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1831] update to download.eclipse.org/releases/2020-12

[eclipse/xtext#1831] update to download.eclipse.org/releases/2020-12

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/builder/BuildAffectionTest.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/buildpath/AbstractJunitLibClasspathAdderTestCase.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/builder/BuildAffectionTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/buildpath/AbstractJunitLibClasspathAdderTestCase.java

Fixed line ending problem in BuildAffection test
Fixed resource leak in AbstractJunitLibClasspathAdderTestCase
Fixes #1114

Fix Test fails on windows

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/smoke/AbstractSmokeTest.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/outline/JvmOutlineTests.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/view/DerivedSourceView.java

[eclipse/xtext#1850] Fix resource leaks

[eclipse/xtext#1850] Fix resource leaks

---

Jenkinsfile

[#1118] use selected target platform for tycho build

[#1118] use selected target platform for tycho build

---

org.eclipse.xtend.core.tests.java8/testdata/testdata/ClassWithVarArgs.java

harmonized fixes for warnings

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202003.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202006.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202009.target

[eclipse/xtext#1851] Add JUnit5 to Xtend target platform

---

org.eclipse.xtend.core.tests.java8/META-INF/MANIFEST.MF
org.eclipse.xtend.core.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.core/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF
org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/ClassFileDebugSourceExtractor.java
org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/ClassFileDebugInfoExtractor.java
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202003.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202006.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202009.target

[eclipse/xtext#1852] Update to ASM 9

[eclipse/xtext#1852] Update to ASM 9

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.24.0.M1

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/AddJunitLibToClasspathQuickfixTest.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/ActiveAnnotationsProcessingInIDETest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/ActiveAnnotationsProcessingInIDETest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/AddJunitLibToClasspathQuickfixTest.java
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/symlinks/pom.xml

update junit in test

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/util/TemporaryFolder.java

fix temp folder security flaw

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1866] update to MWE(2) 1.6.0/2.12.0 M2

[eclipse/xtext#1866] update to MWE(2) 1.6.0/2.12.0 M2

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.24.0.M2

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/GenerateXtend.mwe2

fix generateXtend

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[releng] Update MWE to 1.6.0/2.12.0

---

org.eclipse.xtend.core/src-gen/org/eclipse/xtend/core/services/XtendGrammarAccess.java

regenerated languages

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.24.0.M3

---

org.eclipse.xtend.core/src-gen/org/eclipse/xtend/core/services/XtendGrammarAccess.java

regenerated xtend

---

Jenkinsfile
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202012.target
releng/org.eclipse.xtend.target/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1886] created r202012 target platform

[eclipse/xtext#1886] created r202012 target platform

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/XtendValidationTest.java

Fixes https://github.com/eclipse/xtext-xtend/issues/1147
Signed-off-by: nineninesevenfour <harald.fassler+9974@gmail.com>

Do not flag serialVersionUID as unused (tests)

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202003.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202006.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202009.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202012.target

[eclipse/xtext#1882][2021-03] Update Orbit
DO NOT merge yet

[eclipse/xtext#1882][2021-03] Update Orbit

---

org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/XtendInstallDebugInfoMojoIT.java

commit related to https://github.com/eclipse/xtext-xtend/issues/1029
Signed-off-by: Harald Fassler <harald.fassler+9974@gmail.com>

fix XtendInstallDebugInfoMojoIT (Maven test)

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.25.0.M1

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/editor/XtendNatureAddingEditorCallbackTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/editor/XtendNatureAddingEditorCallbackTest.java

fixed missing super.teardown

---

Jenkinsfile

[eclipse/xtext#1737] archive eclipse test logs also on success

[eclipse/xtext#1737] archive eclipse test logs also on success

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1925] update to MWE 2.12.1.M2

[eclipse/xtext#1925] update to MWE 2.12.1.M2

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.25.0.M2

---

org.eclipse.xtend.core.tests.java8/META-INF/MANIFEST.MF
org.eclipse.xtend.core.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.core/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202003.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202006.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202009.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202012.target

[eclipse/xtext#1934] update to ASM 9.1

[eclipse/xtext#1934] update to ASM 9.1

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.25.0.M3

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.25.0

---

Jenkinsfile
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202103.target
releng/org.eclipse.xtend.target/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1948] create r202103 target platform

[eclipse/xtext#1948] create r202103 target platform

---

Jenkinsfile
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1947] update to 4.20-I-builds

[eclipse/xtext#1947] update to 4.20-I-builds

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202003.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202006.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202009.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202012.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202103.target

[eclipse/xtext#1944] update orbit to 2021-06

[eclipse/xtext#1944] update orbit to 2021-06

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202003.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202006.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202009.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202012.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202103.target

use explicit guice version

---

releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1960]use tycho 2.2 on latest

[eclipse/xtext#1960]use tycho 2.2 on latest

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1947] adapt tps for 2021-06

[eclipse/xtext#1947] adapt tps for 2021-06

---

Jenkinsfile

increased timeout to 6 hrs

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/DispatchCompilerTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/DispatchCompilerTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/jvmmodel/DispatchMethodCompileStrategy.java

[#174] undo changes and a testcase for broken case

[#174] undo changes and a testcase for broken case

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/EqualsWithNullMultiQuickfixTest.xtend
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/RemoveUnnecessaryModifiersMultiQuickfixTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/EqualsWithNullMultiQuickfixTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/RemoveUnnecessaryModifiersMultiQuickfixTest.java

set proper target platform in multi quickfix tests

set proper target platform in multi quickfix tests

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/DispatchCompilerTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/DispatchCompilerTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/jvmmodel/DispatchMethodCompileStrategy.java

[#174] Fix void case where not all cases are covered.

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/javaconverter/ASTParserFactory.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/ASTParserFactory.java

made tests java 16 ready

---

releng/org.eclipse.xtend.maven.parent/pom.xml

update maven-plugin-plugin to 3.6.1

update maven-plugin-plugin to 3.6.1

---

org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/MavenVerifierUtil.java

added workaround for sporadic resolver race problem
https://issues.apache.org/jira/browse/MRESOLVER-153

added workaround for sporadic resolver race problem

---

releng/org.eclipse.xtend.maven.parent/pom.xml

bump maven-javadoc-plugin

---

org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/editor/copyqualifiedname/XtendCopyQualifiedNameService.java

regenerated with Xtend 2.26.0.M1

regenerated with Xtend 2.26.0.M1

---

Jenkinsfile
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202106.target
releng/org.eclipse.xtend.target/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

prepare 2021-06 release tp

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/builder/KeepLocalHistoryTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/builder/KeepLocalHistoryTest.java

[#1198] workaround for keep local history change in platform

[#1198] workaround for keep local history change in platform

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202003.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202006.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202009.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202012.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202103.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202106.target

update to orbit 2021-09

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

use eclipse 2021-09 in target platform
DO NOT MERGE YET

use eclipse 2021-09 in target platform

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/builder/BuildAffectionTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/builder/BuildAffectionTest.java

adapt builder test to new logs. Fixes #1210

adapt builder test to new logs. Fixes #1210

---

releng/org.eclipse.xtend.tycho.parent/pom.xml

update to tycho 2.4

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/javaconverter/ASTParserFactory.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/ASTParserFactory.java

first steps towards testing with java 17

first steps towards testing with java 17

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

use MWE2 2.12.2.M1

---

org.eclipse.xtend.core/src-gen/org/eclipse/xtend/core/serializer/AbstractXtendSemanticSequencer.java
org.eclipse.xtend.core/src-gen/org/eclipse/xtend/core/serializer/AbstractXtendSyntacticSequencer.java

[eclipse/xtext-core#1141] regen langs

[eclipse/xtext-core#1141] regen langs

---

org.eclipse.xtend.core.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.core/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202003.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202006.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202009.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202012.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202103.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202106.target

[eclipse/xtext#1978] update to asm 9.2

[eclipse/xtext#1978] update to asm 9.2

---

org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/MavenVerifierUtil.java

removed workaround for sporadic resolver race problem https://issues.apache.org/jira/browse/MRESOLVER-153

removed workaround for sporadic resolver race problem

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/imports/OrganizeImportsTest.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/DataContentAssistTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/contentassist/DataContentAssistTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/imports/OrganizeImportsTest.java

[#1228] fix tests

---

Jenkinsfile
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202109.target
releng/org.eclipse.xtend.target/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

added target for 2021-09

---

Jenkinsfile
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

update to 4.22 for latest

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

use 2021-12 in latest

---

releng/org.eclipse.xtend.maven.parent/pom.xml

use newer maven-javadoc-plugin

use newer maven-javadoc-plugin

---

releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1994] update to tycho 2.5.0

[eclipse/xtext#1994] update to tycho 2.5.0

---

Jenkinsfile

[eclipse/xtext#2003] trigger nightly from upstream

[eclipse/xtext#2003] trigger nightly from upstream

---

Jenkinsfile

[eclipse/xtext#2005] update to maven 3.8.3

[eclipse/xtext#2005] update to maven 3.8.3

---

Jenkinsfile
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202112.target
releng/org.eclipse.xtend.target/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#2017] repare 2021-12 target && use 4.23 I-Builds

[eclipse/xtext#2017] repare 2021-12 target && use 4.23 I-Builds

---

NOTICE.md
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202003.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202006.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202009.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202012.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202103.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202106.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202109.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202112.target

[eclipse/xtext#2020] update to classgraph 4.8.138

[eclipse/xtext#2020] update to classgraph 4.8.138

---

gradle/eclipse-project-layout.gradle

fix gradle source folder config
Fixes #1264

fix gradle source folder config

---

releng/org.eclipse.xtend.maven.parent/pom.xml

bump maven-compiler-plugin 3.8.1 -> 3.9.0

bump maven-compiler-plugin 3.8.1 -> 3.9.0

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#2025] update to mwe(2) 1.6.2/2.12.2 release

eclipse/xtext#2025] update to mwe(2) 1.6.2/2.12.2 release

---

releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#2021] update to tycho 2.6.0

[eclipse/xtext#2021] update to tycho 2.6.0

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.26.0.M3

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202003.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202006.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202009.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202012.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202103.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202106.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202109.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202112.target

[eclipse/xtext#2029] update to orbit 2022-03

[eclipse/xtext#2029] update to orbit 2022-03

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

update to 2022-03

---

org.eclipse.xtend.ide.tests/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

bumped maven deps

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.26.0.RC1

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.26.0

---

Jenkinsfile
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202203.target
releng/org.eclipse.xtend.target/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#2038] prepare r202203 target

[eclipse/xtext#2038] prepare r202203 target

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#2038] build against 2.24-I-builds on latest

[eclipse/xtext#2038] build against 2.24-I-builds on latest

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202203.target

update to emf 2.29

---

releng/org.eclipse.xtend.maven.parent/pom.xml

bump maven-compiler-plugin to 3.10.1

bump maven-compiler-plugin to 3.10.1

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/builder/BuildAffectionTest.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/compiler/RebuildAffectedResourcesTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/builder/BuildAffectionTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/compiler/RebuildAffectedResourcesTest.java

adapt to needs rebuild changes

adapt to needs rebuild changes

---

org.eclipse.xtend.core.tests/batch-compiler-data/issue750/src/dully/MyJavaClass.java
org.eclipse.xtend.core.tests/batch-compiler-data/test data/test/TestInterface.java
org.eclipse.xtend.core.tests/smoke-suites/org/eclipse/xtend/core/tests/compiler/TypeSystemSmokeTester.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/NoJRESmokeTester.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/SimpleTrace.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/TestCaseCompiler.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/TestClass1Test.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/parsing/LexingTest.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/parsing/ParserTest.java
org.eclipse.xtend.core.tests/testdata/NoPackage.xtend
org.eclipse.xtend.core.tests/testdata/test/Foo.xtend
org.eclipse.xtend.core.tests/xtend-gen/NoPackage.java
org.eclipse.xtend.core.tests/xtend-gen/test/Foo.java
org.eclipse.xtend.ide.tests.data/src/org/eclipse/xtend/ide/tests/data/bug348446/TestClass.java
org.eclipse.xtend.ide.tests.data/src/org/eclipse/xtend/ide/tests/data/contentassist/Foo.java
org.eclipse.xtend.ide.tests.data/src/org/eclipse/xtend/ide/tests/data/contentassist/StaticClassExample.java
org.eclipse.xtend.ide.tests.data/src/org/eclipse/xtend/ide/tests/data/highlighting/TestClassDeprecated.java
org.eclipse.xtend.ide.tests.data/src/org/eclipse/xtend/ide/tests/data/quickfix/QuickFixMe.java
org.eclipse.xtend.ide.tests.data/src/test/Annotation.java
org.eclipse.xtend.ide.tests.data/src/test/Enum1.java
org.eclipse.xtend.ide.tests/batch-compiler-data/test data/test/TestInterface.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/AbstractXtendContentAssistBugTest.java

added missing copyright headers

added missing copyright headers

---

org.eclipse.xtend.examples/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

bump maven-clean-plugin from 3.0.0 to 3.2.0

bump maven-clean-plugin from 3.0.0 to 3.2.0

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#2054] bootstrap against mwe 2.13.0.M1

[eclipse/xtext#2054] bootstrap against mwe 2.13.0.M1

---

releng/org.eclipse.xtend.tycho.parent/pom.xml

update to tycho 2.7.1

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.27.0.M1

---

org.eclipse.xtend.doc/contents/204_activeannotations.html
org.eclipse.xtend.doc/gen_eclipse_help_xtend.launch

regen docs for 2.27

---

releng/org.eclipse.xtend.maven.parent/pom.xml

bump maven-javadoc-plugin to 3.4.0

bump maven-javadoc-plugin to 3.4.0

---

3-maven-tycho-build.sh

[eclipse/xtext-eclipse#1842] remove test failure ignore

[eclipse/xtext-eclipse#1842] remove test failure ignore

---

releng/org.eclipse.xtend.tycho.tests.parent/pom.xml

no pde api

---

org.eclipse.xtend.examples/.settings/org.eclipse.core.resources.prefs
org.eclipse.xtend.ide.tests.data/.settings/org.eclipse.core.resources.prefs
org.eclipse.xtend.m2e/.settings/org.eclipse.core.resources.prefs
org.eclipse.xtend.standalone/.settings/org.eclipse.core.resources.prefs
org.eclipse.xtend.swtbot/.settings/org.eclipse.core.resources.prefs
releng/org.eclipse.xtend.target/.settings/org.eclipse.core.resources.prefs

added missing org.eclipse.xtext.testlanguages.ide/.settings/org.eclipse.core.resources.prefs

added missing org.eclipse.xtext.testlanguages.ide/.settings/org.eclipse.core.resources.prefs

---

org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/XtendCompilerMojoIT.java
org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/XtendCompilerMojoTraceIT.java

fix maven-verifier deprecations

fix maven-verifier deprecations

---

NOTICE.md
org.eclipse.xtend.core.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.core/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202003.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202006.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202009.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202012.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202103.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202106.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202109.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202112.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202203.target

[eclipse/xtext#2053] Update to ASM 9.3 [eclipse/xtext#2039] Update to Orbit 2022-06

[eclipse/xtext#2053] Update to ASM 9.3 [eclipse/xtext#2039] Update to Orbit 2022-06

---

org.eclipse.xtend.maven.plugin/pom.xml
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202003.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202006.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202009.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202012.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202103.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202106.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202109.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202112.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202203.target

[eclipse/xtext#2055]simplify dependencies to asm

[eclipse/xtext#2055]simplify dependencies to asm

---

org.eclipse.xtend.examples/.classpath

fixed warning

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

update to MWE 2.13.0.M2

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.27.0.M2

---

releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#2060] update to tycho 2.7.2

[eclipse/xtext#2060] update to tycho 2.7.2

---

releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#2064] update to tycho 2.7.3

[eclipse/xtext#2064] update to tycho 2.7.3

---

org.eclipse.xtend.core.tests/.settings/org.eclipse.xtend.core.Xtend.prefs
org.eclipse.xtend.core/.settings/org.eclipse.xtend.core.Xtend.prefs

cleanup xtend preferences

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#2061] Bootstrap against MWE 2.13.0 release

[eclipse/xtext#2061] Bootstrap against MWE 2.13.0 release

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.27.0.M3

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.27.0

---

Jenkinsfile
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202206.target
releng/org.eclipse.xtend.target/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#2068] prepare r202206 target

[eclipse/xtext#2068] prepare r202206 target

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202206.target

[eclipse-pde/eclipse.pde#102] drop removed api.tools.ee.feature

[eclipse-pde/eclipse.pde#102] drop removed api.tools.ee.feature

---

releng/org.eclipse.xtend.maven.parent/pom.xml

bump maven-enforcer-plugin to 3.1.0

bump maven-enforcer-plugin to 3.1.0

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202003.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202006.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202009.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202012.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202103.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202106.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202109.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202112.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202203.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202206.target
releng/org.eclipse.xtend.tycho.tests.parent/pom.xml

[eclipse/xtext-xtend#1355] configure tests to include xtext logging

[eclipse/xtext-xtend#1355] configure tests to include xtext logging

---

releng/org.eclipse.xtend.tycho.parent/pom.xml

update to tycho 2.7.4

---

NOTICE.md
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202003.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202006.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202009.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202012.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202103.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202106.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202109.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202112.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202203.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202206.target

[eclipse/xtext#2071] update to orbit 2022-09

[eclipse/xtext#2071] update to orbit 2022-09

---

org.eclipse.xtend.ide.tests/pom.xml

bumped maven-dependency-plugin

bumped maven-dependency-plugin

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.28.0.M1

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/formatting/preferences/AbstractModifyDialogTab.java

[#1362] workaround for changed internal api in jdt

[#1362] workaround for changed internal api in jdt

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.28.0.M2

---

releng/org.eclipse.xtend.maven.parent/pom.xml

bump maven-javadoc-plugin to 3.4.1

bump maven-javadoc-plugin to 3.4.1

---

org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/XtendFormatter.java
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target

change baseclass for xbase formatter: regen impls

change baseclass for xbase formatter: regen impls

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.28.0.M3

---

Jenkinsfile
org.eclipse.xtend.m2e/src/org/eclipse/xtend/m2e/XtendProjectConfigurator.java

m2e: use reflection also for old method

m2e: use reflection also for old method

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.28.0

---

Jenkinsfile
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202209.target
releng/org.eclipse.xtend.target/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#2092] prepare r202209 target

[eclipse/xtext#2092] prepare r202209 target

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#2092] switch latest to 4.26 i-builds

[eclipse/xtext#2092] switch latest to 4.26 i-builds

---

releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#2096] update to tycho 2.7.5

[eclipse/xtext#2096] update to tycho 2.7.5

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#2092] update to 2022-12 in latest

[eclipse/xtext#2092] update to 2022-12 in latest

---

releng/org.eclipse.xtend.tycho.parent/pom.xml

ditch non used source-feature plugin. See [eclipse/xtext#2102]

ditch non used source-feature plugin. See [eclipse/xtext#2102]

---

NOTICE.md
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201909.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201912.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202003.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202006.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202009.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202012.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202103.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202106.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202109.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202112.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202203.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202206.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202209.target

[eclipse/xtext#2089] Update to Orbit 2022-12 incl new classgraph & gson

[eclipse/xtext#2089] Update to Orbit 2022-12 incl new classgraph & gson

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/buildpath/XtendClasspathContainer.java

Closes #1387 
Signed-off-by: Sebastian Zarnekow <sebastian.zarnekow@gmail.com>

[#1387] Remove outdated JavaDoc location from XtendLibCPContainer

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.29.0.M1

---

NOTICE.md
org.eclipse.xtend.core.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.core/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202203.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202206.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202209.target

[eclipse/xtext#2104] update to asm 9.4

[eclipse/xtext#2104] update to asm 9.4

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java

[#1393] added missing super.tearDown to test

[#1393] added missing super.tearDown to test

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.29.0.M2

---

org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/AbstractXtendCompilerMojo.java

switch compiler level default to 11

switch compiler level default to 11

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/ConfiguredCompilerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/batch/TestBatchCompiler.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/imports/ImportsCollectorTests.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/typesystem/BoundTypeArgumentMergerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/typesystem/CommonSuperTypeTest.xtend
org.eclipse.xtend.core.tests/testdata/testdata/ClassWithEnum.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/ConfiguredCompilerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/batch/TestBatchCompiler.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/imports/ImportsCollectorTests.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/BoundTypeArgumentMergerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/CommonSuperTypeTest.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/Bug435184Test.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/ContentAssistInElseBlockTest.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/ContentAssistInLambdaTest2.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/DataContentAssistTest.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/hover/JvmAnnotationReferencePrinterTest.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/hover/XtendHoverDocumentationProviderTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/contentassist/Bug435184Test.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/contentassist/DataContentAssistTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/hover/JvmAnnotationReferencePrinterTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/hover/TestingXbaseHoverProvider.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/hover/XtendHoverDocumentationProviderTest.java

clean java 11 guards in tests

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#2106] Update to MWE 2.14.0.M1

[eclipse/xtext#2106] Update to MWE 2.14.0.M1

---

org.eclipse.xtend.doc/contents/204_activeannotations.html

regen docs for 2022-12

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202203.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202206.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202209.target

use fixed asm 9.4 version from orbit m3

use fixed asm 9.4 version from orbit m3

---

releng/org.eclipse.xtend.maven.parent/pom.xml

bump maven-plugin-plugin

---

org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/XtendInstallDebugInfoMojoIT.java
org.eclipse.xtend.maven.plugin/src/test/resources/it/install_debug_info/simple_smap/pom.xml

[#1391] switch test to java 11

[#1391] switch test to java 11

---

releng/org.eclipse.xtend.tycho.parent/pom.xml

use tycho 2.7.5 everywhere

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202203.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202206.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202209.target

[eclipse/xtext#2112] Fix Orbit signing problem

[eclipse/xtext#2112] Fix Orbit signing problem

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.29.0.M3

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202203.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202206.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202209.target

[eclipse/xtext#2112] switch back to orbit 2022-12

[eclipse/xtext#2112] switch back to orbit 2022-12

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#2107] update to mwe 2.14.0 release

[eclipse/xtext#2107] update to mwe 2.14.0 release

---

org.eclipse.xtend.core/generator/org/eclipse/xtend/core/parser/JFlexLoader.java

replace File.createTempFile with Files.createTempFile.toFile

replace File.createTempFile with Files.createTempFile.toFile

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.29.0

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/typesystem/ActualTypeArgumentCollectorTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/typesystem/RawIterable.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/ActualTypeArgumentCollectorTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/CharIterable.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/MapType.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/ChangeListenerAddingFileSystemSupportTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/ChangeListenerAddingFileSystemSupportTest.java

fix some warnings

---

Jenkinsfile
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202212.target
releng/org.eclipse.xtend.target/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#2120] prepare r202212 target

[eclipse/xtext#2120] prepare r202212 target

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/compiler/batch/XtendBatchCompiler.java
org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/AbstractXtendCompilerMojo.java

[#646] Fix Maven deprecations and drop Java 8 support

[#646] Fix Maven deprecations and drop Java 8 support

---

org.eclipse.xtend.standalone/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202203.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202206.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202209.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202212.target

Remove Dependency to deprecated junit plugins

Remove Dependency to deprecated junit plugins

---

org.eclipse.xtend.performance.tests/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202203.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202206.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202209.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202212.target

[eclipse/xtext#2125] bump mwe version in manifest

[eclipse/xtext#2125] bump mwe version in manifest

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#2120] update to 2023-03 in latest

[eclipse/xtext#2120] update to 2023-03 in latest

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/JavaRefactoringIntegrationTest.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/buildpath/JavaClasspathTest.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/editor/XbaseEditorOpenClassFileTest.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/navigation/OpenEditorTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/editor/XbaseEditorOpenClassFileTest.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/editor/XtendEditorErrorTickUpdater.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/wizards/StubUtilityProxy.java

remove more outdated code switches for old targets

remove more outdated code switches for old targets

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/compiler/batch/Main.java

Added support for verbose mode when called from main

Added support for verbose mode when called from main

---

org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/AbstractXtendCompilerMojo.java

more java 11 cleanups

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202203.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202206.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202209.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r202212.target

[eclipse/xtext#2118] update to orbit 2023-03

[eclipse/xtext#2118] update to orbit 2023-03

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.30.0.M1

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/compiler/batch/XtendBatchCompiler.java

fix java deprecations

---

releng/org.eclipse.xtend.maven.parent/pom.xml

bump maven-plugin-plugin 3.7.1

bump maven-plugin-plugin 3.7.1

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/builder/JavaProjectPreferencesInitializer.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/formatting/preferences/AbstractProfileManager.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/preferences/XtendPreferenceStoreAccess.java

fix Default/Instance/Configuration Scope deprecations

fix Default/Instance/Configuration Scope deprecations

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/compiler/RebuildAffectedResourcesTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/compiler/RebuildAffectedResourcesTest.java

[#1212] add workaround for RebuildAffectedResourcesTest flakyness

[#1212] add workaround for RebuildAffectedResourcesTest flakyness

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.30.0.M2

---

releng/org.eclipse.xtend.maven.parent/pom.xml

bump maven-enforcer-plugin

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.30.0.M3

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.30.0.RC1

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.30.0.RC2

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[releng] Bootstrap against 2.30.0
