eclipse/xtext-xtend

org.eclipse.xtend.ide.common/src/org/eclipse/xtend/ide/common/highlighting/XtendHighlightingCalculator.java

If 'name' feature does not exist for the EClass, a null reference is passed into highlightFeature, which causes a NPE when NodeModelUtils is called.

[478377] Add null guard condition

---

org.eclipse.xtend.m2e/META-INF/MANIFEST.MF

Due to availability of version 1.7.0 and for further 1.x versions

[480472] Dependency upper range for org.eclipse.m2e.maven.runtime opened

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/view/DerivedSourceView.java

Fixed the generated code view. the annotation ruler column now can show the error messages when hovering.
Fixes https://bugs.eclipse.org/bugs/show_bug.cgi?id=381156

Show Annotation Hovers in Generated Code View

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBug406762Test.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBug406762Test.java

Tests to show the problem went away, thanks to
https://github.com/eclipse/xtext-extras/pull/69
Closes #68 
Task-Url: https://github.com/eclipse/xtext-xtend/issues/68
Signed-off-by: Lorenzo Bettini <lorenzo.bettini@gmail.com>

#68: Unexpected "Invalid return inside throw."

---

org.eclipse.xtend.examples/.gitignore

When importing Xtend projects the sources for the example projects are generated. So far they are not checked in. I propose that we do not check in them, but ignore them.

Ignore xtend-gen content for example projects

---

org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/autobuild/MultiModuleTest.java
org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/completion/XtendCodeContextTypeTest.java
org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/completion/XtendCompletionTest.java
org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/config/GradleBuildFileUtilTest.java
org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/config/XtendLibraryManagerTest.java
org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/config/XtendSupportConfigurableTest.java
org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/documentation/XtendDocumentationTest.java
org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/execution/TraceBasedConfigurationProducerTest.java
org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/findUsages/XtendFindUsagesTest.java
org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/highlighting/XtendHighlightingLexerTest.java
org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/intentions/IntentionsTest.java
org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/javaconverter/IdeaJavaConverterTest.java
org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/macro/Bug473721.java
org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/macro/IdeaProcessorProviderTest.java
org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/navigation/IdeaTraceTest.java
org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/navigation/XtendNavigationTest.java
org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/psi/XtextPsiReferenceTest.java

Changes due to regenerated Xtend code.
Base class com.intellij.testFramework.UsefulTestCase extends
junit.framework.TestCase, which defines the static assert-methods.

References on j.f.Assert replaced by j.f.TestCase

---

org.eclipse.xtend.caliper.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.core.tests.java8/META-INF/MANIFEST.MF
org.eclipse.xtend.core.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.core/plugin.properties
org.eclipse.xtend.doc/plugin.properties
org.eclipse.xtend.examples/plugin.properties
org.eclipse.xtend.examples/projects/xtend-annotation-examples-client/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/projects/xtend-examples/META-INF/MANIFEST.MF
org.eclipse.xtend.gwt.feature/feature.properties
org.eclipse.xtend.ide.common/plugin.properties
org.eclipse.xtend.ide.swtbot.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.ide.tests.data/META-INF/MANIFEST.MF
org.eclipse.xtend.ide.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.ide/plugin.properties
org.eclipse.xtend.m2e/plugin.properties
org.eclipse.xtend.performance.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.sdk.feature/feature.properties
org.eclipse.xtend.standalone/META-INF/MANIFEST.MF
org.eclipse.xtend.swtbot/META-INF/MANIFEST.MF

Must be Eclipse Xtext instead of Eclipse Xtend, see #48

[502897] Bundle-Vendor changed

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/wizards/AbstractNewXtendElementWizard.java

With this change the cursor is placed in the element body without selection:

[#43] Set cursor without selection after opening the editor for a new file

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBug440006Test.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/XtendCompilerTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBug440006Test.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/XtendCompilerTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/compiler/XtendCompiler.java
org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/XtendCompilerMojoIT.java

Java code generated from Xtend routinely contains output
like:
public CharSequence packageDefinition() {
StringConcatenation _builder = new StringConcatenation();
_builder.append("package ");
String _packageName = this.type.getPackageName();
_builder.append(_packageName, "");
_builder.append(";");
return _builder;
}
While StringConcatenation will detect the fact the indentation
string is empty, it is at the cost of runtime performance.
Before emitting the call to StringConcatenation, check if our
literal would end up being an empty string and if it would,
call the no-indentation append() variant instead.
Signed-off-by: Robert Varga <nite@hq.sk>

[507077] Do not emit empty concatenation

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/XtendCompilerTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/XtendCompilerTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/compiler/XtendCompiler.java

The XtendCompiler failed with an exception when used without variable
declaration for a feature call.
The new test XtendCompilerTest#testRichStringMemberFeatureCall
reproduces the situation.

[492072] Fixed compile issue for RichString in feature calls

---

org.eclipse.xtend.core.tests/batch-compiler-data/bug396747/test/EmptyFile.xtend
org.eclipse.xtend.ide.tests/batch-compiler-data/bug396747/test/EmptyFile.xtend
org.eclipse.xtend.ide.tests/batch-compiler-data/test data/test/B.xtend
org.eclipse.xtend.ide.tests/batch-compiler-data/test data/test/C.xtend
org.eclipse.xtend.ide.tests/batch-compiler-data/test data/test/JavaB.java
org.eclipse.xtend.ide.tests/batch-compiler-data/test data/test/OtherTypes.xtend
org.eclipse.xtend.ide.tests/batch-compiler-data/test data/test/TestInterface.java
org.eclipse.xtend.ide.tests/batch-compiler-data/test data/test/XtendA.xtend
org.eclipse.xtend.ide.tests/batch-compiler-data/test data/test/XtendC.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/compiler/batch/XtendCompilerAntTaskTest.java

Fixed broken XtendCompilerAntTaskTest. Added missing test resources.Fixes #126

Fixed broken XtendCompilerAntTaskTest. Added missing test resources.Fixes #126

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/imports/OrganizeImportsTest.xtend
org.eclipse.xtend.ide.tests/longrunning/xtend-gen/org/eclipse/xtend/ide/tests/imports/OrganizeImportsTest.java

This adds tests for the erroneus cases described in https://bugs.eclipse.org/bugs/show_bug.cgi?id=460455
The first case is addressed by https://github.com/eclipse/xtext-extras/pull/105.
The second case is not fixed yet and therefore disabled. Likely it has to be solved in ConflictResolver.

[460455] Add test cases

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/javaconverter/JavaConverterTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/javaconverter/JavaConverterTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/javaconverter/ASTFlattenerUtils.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/ASTFlattenerUtils.java

[477445] dont use richstring inside annotations for j2x

[477445] dont use richstring inside annotations for j2x

---

org.eclipse.xtend.ide.common/src/org/eclipse/xtend/ide/common/highlighting/XtendHighlightingCalculator.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/highlighting/XtendHighlightingCalculatorTest.java

do rich string highlighting inside constrcutors as well. fixes #49

do rich string highlighting inside constrcutors as well. fixes #49

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/scoping/RecordingTypeScope.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/scoping/XtendImportedNamespaceScopeProvider.java

[457930] Better recording of non resolved imported names in xtend

[457930] Better recording of non resolved imported names in xtend

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/contentassist/javadoc/XtendJavaDocProposalFactory.java

[446145] fixed replacement context length calculation for javadoc proposals

[446145] fixed replacement context length calculation for javadoc proposals

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/XtendFormatterBugTests.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendFormatterBugTests.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/formatting2/XtendFormatter.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/XtendFormatter.java

[402917] Fixed Formatting of extension keyword in Xtend

[402917] Fixed Formatting of extension keyword in Xtend

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/tasks/XtendTaskFinderTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/tasks/XtendTaskFinderTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/XtendRuntimeModule.xtend
org.eclipse.xtend.core/src/org/eclipse/xtend/core/tasks/XtendTaskFinder.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/XtendRuntimeModule.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/tasks/XtendTaskFinder.java

[479942] Add Support for Task Tags inside Rich String Comments in Xtend

[479942] Add Support for Task Tags inside Rich String Comments in Xtend

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/builder/XtendParallelBuilderParticipant.java

fixes https://github.com/eclipse/xtext-eclipse/issues/225

use reverse lookup map to find source files for generated files

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/wizards/AbstractNewXtendElementWizardPage.java

[442543] Strip Type Parameter from Filename in New Xtend File Wizard

[442543] Strip Type Parameter from Filename in New Xtend File Wizard

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/serializer/AbstractXtendTestData.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/serializer/XtendSyntacticSequencer.java

[445698] Xtend serializer produces ambiguous syntax related to anonymous classes

[445698] Xtend serializer produces ambiguous syntax related to anonymous classes

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/JavaRefactoringIntegrationTest.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/refactoring/XtendReferenceUpdater.xtend
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/refactoring/XtendReferenceUpdater.java

Sort References on Rename Refactoring to Prevent NPE when Anon Inner Class Constructors are Involved. Fixes https://github.com/eclipse/xtext-core/issues/300

Sort References on Rename Refactoring to Prevent NPE

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBug426073Test.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBug426073Test.java

[426073] [xtend][compiler] The generated Java code contains a conflict between a field name and an imported class name

[426073] [xtend][compiler] The generated Java code contains a conflict between a field name and an imported class name

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/refactoring/XtendFileRenameParticipant.java

[483783] Fixed MalformedTreeException that lead to File Rename on Xtend File not working

[483783] Fixed MalformedTreeException that lead to File Rename on Xtend File not working

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/typesystem/OverrideHelperTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/XtendValidationTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/OverrideHelperTest.java

[515801] ClassCastException in OverrideHelper.findOverriddenOperation and AbstractResolvedOperation.getOverriddenAndImplementedMethodCandidates

[515801] ClassCastException in OverrideHelper.findOverriddenOperation and AbstractResolvedOperation.getOverriddenAndImplementedMethodCandidates

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/contentassist/XtendProposalProvider.java

[ContentAssist] Content assist proposes classes instead of interfaces when extending an interface
Fixes https://github.com/eclipse/xtext-eclipse/issues/258

[ContentAssist] Content assist proposes classes instead of interfaces when extending an interface

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/XtendFormatterBugTests.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendFormatterBugTests.java

This commit only adds a test. 
The actual fix is https://github.com/eclipse/xtext-core/issues/301
Signed-off-by: Moritz Eysholdt <moritz.eysholdt@typefox.io>

fixed #194 [formatter] Formatting a long line messes up the indentation

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerXtendIssue230Test.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerXtendIssue230Test.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/typesystem/XtendTypeComputer.java

Reassignment of checked types is missing in template expression's 'ELSEIF' #230

Reassignment of checked types is missing in template expression's 'ELSEIF' #230

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/AbstractXbaseContentAssistTest.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/Bug364966Test.java

fixed content assist tests after changes to collection literals

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/folding/XtendFoldingRegionProviderTest.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/editor/XtendFoldingRegionProvider.java

[#279][488160] Enabled Folding for Closures, Set and List Literals, Rich-Strings

[#279][488160] Enabled Folding for Closures, Set and List Literals, Rich-Strings

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java

In order to use the isRelevantAnnotationTarget() function within subtypes of XtendValidator, the visibility of this function should be changed from "private" to "protected".

Change the visibility of isRelevantAnnotationTarget.

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/GenerateXtend.mwe2
org.eclipse.xtend.ide/plugin.xml
org.eclipse.xtend.ide/plugin.xml_gen
org.eclipse.xtend.ide/src-gen/org/eclipse/xtend/ide/AbstractXtendUiModule.java
org.eclipse.xtend.ide/src-gen/org/eclipse/xtend/ide/editor/XtendEditor.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/XtendUiModule.xtend
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/XtendUiModule.java

Added the new EditorFragment2 to GenerateXtend.mwe2 and configured the generated XtendEditor for the StratumBreakpointAdapterFactory.
Main part of the fix for [eclipse/xtext-eclipse#463] is in pull request [eclipse/xtext-core#561]
Signed-off-by: Florian Stolte <fstolte@itemis.de>

[eclipse/xtext-eclipse#463] Adjusted Xtend to the modifications done for this issue

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/macro/JdtBasedProcessorProvider.xtend
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/macro/JdtBasedProcessorProvider.java

prevent JdtBasedProcessorProvider from exploding when using non efs filesystems
https://github.com/eclipse/xtext-xtend/issues/50

prevent JdtBasedProcessorProvider from exploding when using non efs filesystems

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/GenerateXtend.mwe2

Adjustments due to the changes in [eclipse/xtext-core#574]:
- removed reference to the EditorFragment2 from Xtend generator.
Signed-off-by: Florian Stolte <fstolte@itemis.de>

[eclipse/xtext-eclipse#463] Removed references to EditorFragment2

---

org.eclipse.xtend.caliper.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/projects/xtend-annotation-examples-client/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/projects/xtend-examples/META-INF/MANIFEST.MF
org.eclipse.xtend.ide.swtbot.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.ide.tests.data/META-INF/MANIFEST.MF
org.eclipse.xtend.ide.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.ide/META-INF/MANIFEST.MF
org.eclipse.xtend.m2e/META-INF/MANIFEST.MF
org.eclipse.xtend.performance.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.swtbot/META-INF/MANIFEST.MF

[eclipse/xtext#1152] Java 9 - Added Automatic-Module-Name header

---

org.eclipse.xtend.ide/src-gen/org/eclipse/xtend/ide/AbstractXtendUiModule.java

Regenerated xtend language due to fix for the faulty binding generation in issue [eclipse/xtext-eclipse#463]
Signed-off-by: Florian Stolte <fstolte@itemis.de>

[eclipse/xtext-eclipse#463] Fixed faulty editor binding

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/editor/copyqualifiedname/XtendCopyQualifiedNameServiceTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/editor/copyqualifiedname/XtendCopyQualifiedNameServiceTest.java

Test was forgotton to update inside eclipse/xtext-eclipse#145.
Change-Id: I91a76ed2b38cd3d9ef51df7db4a9f368ad6c7348

[#342] Update test by testing nbew implementation.

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/editor/DirtyStateEditorValidationTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/editor/DirtyStateEditorValidationTest.java

The test validates that the editors synchronize between one another even
if the file is not saved. But it has to assume that the build is run
before the editors are opened. Seems on CLI the autobuild is not run
fast enough and in result the "waitForAutobuild" is passed before the
build has even started. But this autobuild is not the intention of the
test, it is part of the setup. Hence we just initiate a build manually
just as the other test cases do, too. And wait for this build to finish.
Afterwards the testss succeed on CLI as well as in eclipse.
Change-Id: I13b8362a7fca8d54d532a1b789f1a3456a8a042f

[#340] Fix test by ensure that preconditions are met.

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/editor/copyqualifiedname/XtendCopyQualifiedNameServiceTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/editor/copyqualifiedname/XtendCopyQualifiedNameServiceTest.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/XtendUiModule.xtend
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/XtendUiModule.java

Bind deprecated interfaces in addition to new ones.
Change-Id: Idc44f9c9e27d8250e783f7c6d01fc414309aef43

[eclipse/xtext-eclipse#517] Bind deprecated interfaces.

---

org.eclipse.xtend.ide/plugin.xml

- Add corresponding menu contribution (similar to the Package Explorer
context menu contribution) to the org.eclipse.xtend.ide/plugin.xml file.

[#350] Add the 'Convert to Xtend' context menu to the Project Explorer.

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java

In order to be used by the DSL validator, the `getOutermostType` function's visibility should be changed to `protected`.

Change to protected the visibility of the getOutermostType function.

---

README.md
org.eclipse.xtend.ide.swtbot.tests/swtbot/src/org/eclipse/xtend/ide/swtbot/EclipseAPI.java
org.eclipse.xtend.ide.swtbot.tests/swtbot/src/org/eclipse/xtend/ide/swtbot/api/MainMenuAPI.java
org.eclipse.xtend.ide.swtbot.tests/swtbot/src/org/eclipse/xtend/ide/swtbot/api/preferences/PreferencesDialogAPI.java
org.eclipse.xtend.ide.swtbot.tests/swtbot/src/org/eclipse/xtend/ide/swtbot/api/preferences/XtendFormatterPreferenceEditDialogAPI.java
org.eclipse.xtend.ide.swtbot.tests/swtbot/src/org/eclipse/xtend/ide/swtbot/api/preferences/XtendFormatterPreferencePageAPI.java
org.eclipse.xtend.ide.swtbot.tests/swtbot/src/org/eclipse/xtend/ide/swtbot/lowlevel/XtextSWTBot.java
org.eclipse.xtend.ide.swtbot.tests/swtbot/src/org/eclipse/xtend/ide/swtbot/lowlevel/XtextSWTBotShell.java
org.eclipse.xtend.ide.swtbot.tests/swtbot/src/org/eclipse/xtend/ide/swtbot/lowlevel/XtextSWTWorkbenchBot.java
org.eclipse.xtend.ide.swtbot.tests/swtbot/src/org/eclipse/xtend/ide/tests/AbstractSwtBotTest.java
org.eclipse.xtend.ide.swtbot.tests/swtbot/src/org/eclipse/xtend/ide/tests/preferences/FormatterPreferencesTest.java
org.eclipse.xtend.ide.swtbot.tests/xtend.ide.tests.slow (SWTBot).launch
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/formatting/preferences/FormatterModifyDialog.java

Implemented the dialog in a way such that it is compatible with Eclipse
Photon as well as with older Eclipse versions. Some nasty reflection is
needed to maintain backwards compatibility. Should be replaced with
Xtext based implementation in future.
Change-Id: Icecbf625da3fd2244ae507c83c0c90e481b5f38e

eclipse/xtext-eclipse#539 Make dialog compatible with Eclipse Photon.

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/performance/XtendFileGenerator.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/ModifierValidationTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/ValidationBug437678Test.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/performance/XtendFileGenerator.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/ModifierValidationTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/ValidationBug437678Test.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/IssueCodes.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/ModifierValidator.java

Extend the Xtend modifier validator with "Redundant modifiers" to raise warnings in case of:
- 'final' in combination with 'val'
- 'private' on fields
- 'public' on methods
- 'public' on classes
- 'def' in combination with 'override'
- Implement corresponding ModifierValidationTest test cases.
- Eliminate redundant modifiers from the Xtend test data in order not to break existing test cases.

[#361] Implement "Redundant modifiers" Xtend validation rule.

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/AbstractFileSystemSupport.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/AbstractFileSystemSupport.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/EclipseFileSystemTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/EclipseFileSystemTest.java

[#383] Fixed FileSystemSupport.getPath() to work with multiple projects

[#383] Fixed FileSystemSupport.getPath() to work with multiple projects

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/ReadWriteAccessTest.java

The included unit tests are related to the change of the
"isLocallyUsed()" function within xbase-extras (PR 232).
Any field or local variable that is used as a left operand
of the assignment operator is not considered as being used.
see https://github.com/eclipse/xtext-extras/pull/232

Unit tests for unused field and local variables.

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/ModifierValidator.java
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/quickfix/XtendQuickfixProvider.java

- Extend the ModifierValidator to pass the redundant modifier as issue
data from the validator to the quickfix provider.
- Extend the XtendQuickfixProvider to provide quickfixes to remove the
redundant Xtend member modifier.
- Implement corresponding Xtend QuickfixTest test cases.

[#370] Provider quickfixes to remove redundant Xtend member modifiers.

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java

- Eliminate duplicated code by introducing the 'declaringType' local
variable.

[NONE] Refactor the XtendValidator checkModifiers validation rules.

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/XtendValidationTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/ModifierValidator.java
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java

- Extend the Xtend ModifierValidator to recognize the 'public' modifier
on interfaces and constructors as 'Redundant modifier'.
- Implement corresponding QuickfixTest test cases.
- Adapt the input data of the already existing test cases in order not
to break them.

[#361] 'Redundant modifier' validation rule on interfaces/constructors.

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/ModifierValidationTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/ModifierValidationTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/IssueCodes.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/ModifierValidator.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendConfigurableIssueCodes.java
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/quickfix/XtendQuickfixProvider.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/validator/preferences/XtendValidatorConfigurationBlock.java

- Since the validation rule mostly targets visibility modifiers matching
the defaults, using the 'Unnecessary modifier' notation is more suitable
than the 'Redundant modifier' notation.

[#361] Rename the 'Redundant modifier' to 'Unnecessary modifier'.

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/ParallelFileSystemSupport.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/ParallelFileSystemSupport.java

ActiveAnnotationProcessors might run in parallel. Read operations should
wait until all write operations are ready to avoid race conditions.

[eclipse/xtext-eclipse#599] Support waiting operation.

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target

[eclipse/xtext-eclipse#543] Updated Oxygen Target to 3a

[eclipse/xtext-eclipse#543] Updated Oxygen Target to 3a

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/quickfix/XtendQuickfixProvider.java

made multi quickfix not update references and related files since it only removed redundant modifiers that dont change anything outside

[#408] Fixed CCE in Redundant Modifier Quickfix

---

org.eclipse.xtend.caliper.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.core.tests.java8/META-INF/MANIFEST.MF
org.eclipse.xtend.core.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.core/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF

[eclipse/xtext#1190] Narrowed the version range for asm to [6.1.1,6.2.0)

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/build/XtendIncrementalBuilderTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/build/XtendIncrementalBuilderTest.java

[eclipse/xtext-core#716] Fixed tests after changes in xtext-core

[eclipse/xtext-core#716] Fixed tests after changes in xtext-core

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/editor/XtendEditorDoubleClickTextSelectionTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/editor/XtendEditorDoubleClickTextSelectionTest.java

- Implement XtendEditorDoubleClickTextSelectionTest test cases based on
the AbstractEditorDoubleClickTextSelectionTest abstract test case to
test the customized XtendDoubleClickStrategyProvider behaviour.

[https://github.com/eclipse/xtext-eclipse/issues/654] Xtend test cases.

---

org.eclipse.xtend.examples/build.properties

[#448] Fixed broken example packaging

[#448] Fixed broken example packaging

---

org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/AbstractXtendMojo.java
org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/XtendCompile.java
org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/XtendInstallDebugInfo.java
org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/XtendTestCompile.java
org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/XtendTestInstallDebugInfo.java

[#468] Marked Mojos as Threadsafe and introduced a lock to ensure singlethreaded execution

[#468] Marked Mojos as Threadsafe and introduced a lock to ensure singlethreaded execution

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTestBuilder.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTestBuilder.java

- Implement useXtendTypeSignature Quickfix test case to ensure that the
Quickfix creates the missing method signature in the Xtend notation
instead of using the Java notation.
- Adjust the QuickfixTestBuilder test helper class to consider only the
first '|' symbol as a position marker to be able to use further '|'
symbols in Xtend lambda expressions.

[402920] Add QuickfixTest to ensure the creation of Xtend notation.

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/XtendRichStringFormatterTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/richstring/RichStringProcessorTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendRichStringFormatterTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/formatting2/RichStringFormatter.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/Chunk.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/Line.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/LineModel.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/RichStringFormatter.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/RichStringToLineModel.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/SemanticText.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/SemanticWhitespace.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/TemplateWhitespace.java
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java

Implement a workaround to avoid exception. Formatting is not 100%
correct but at least the formatting is done at all (one missing tab).
Added test case to verify that no exception is raised.
Also added TODO comments explaining what and why it was done.

[eclipse/xtext-core#710] Workaround for exception.

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/formatting/preferences/BlankLinesTab.java

The checkbox preference has no following input widget, therefore no
colon is needed.
Signed-off-by: Michael Keppler <Michael.Keppler@gmx.de>

Remove superfluous colon from preference label

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/quickfix/XtendQuickfixProvider.java

- Extend the XtendQuickfixProvider to provide Quickfixes to change the
return type of an Xtend method to void (also executable in batch mode).
- Implement corresponding Xtend QuickfixTest test cases.

[#504] Provide Quickfixes to change JUnit methods' return type to void.

---

org.eclipse.xtend.ide.common/META-INF/MANIFEST.MF

[#1238] Restrict org.antlr.runtime version to 3.2.0

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/JUnitMethodReturnTypeValidationTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/JUnitMethodReturnTypeValidationTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java

- Modify the checkJUnitMethodReturnType Xtend validation rule to ensure
that the 'JUnit Method Return Type Validation Check' doesn't report any
follow up issues in case of an unknown return type.
- Implement corresponding JUnitMethodReturnTypeValidationTest test case.

[#516] Improve the checkJUnitMethodReturnType Xtend validation rule.

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/ModifierValidator.java

In a specific DSL extending Xtend, the implicit modifiers may be
different than the ones that are hardcoded into Xtend. This patch add
protected functions in order to enable the overriding of the modifier
validator.

[validator] Enable overriding of the implicit modifier validation.

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/hover/XtendHoverDocumentationProviderTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/hover/XtendHoverDocumentationProviderTest.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/hover/XtendHoverDocumentationProvider.java

[eclipse/xtext-eclipse#782] fixed javadoc links in javadoc of types. fixed javadoc links to constructors

[eclipse/xtext-eclipse#782] fixed javadoc links in javadoc of types. fixed javadoc links to constructors

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/AbstractXtendRenameRefactoringTest.java
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/JavaRefactoringIntegrationTest.java
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/RefactoringIntegrationTest.java
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/RenameJvmOperationTest.xtend
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/RenameResourceTest.xtend
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/XImportSectionUpdateOnRenameTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/refactoring/RenameJvmOperationTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/refactoring/RenameResourceTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/refactoring/XImportSectionUpdateOnRenameTest.java

- Eliminate duplicated code by introducing the
AbstractXtendRenameRefactoringTest abstract base class.
- Add missing/Update exsiting copyright headers.

Refactoring the Xtend IDE rename refactoring test cases.

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/JavaRefactoringIntegrationTest.java

- The following test case have been ignored, but now it is running
successfully (tested it also manually).

Activate ignored Xtend Rename Refactoring test case.

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/JdtBasedProcessorProviderTest.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/MoreActiveAnnotationsTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/JdtBasedProcessorProviderTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/MoreActiveAnnotationsTest.java

Test fails when executed before any other that initialize the target platform.

Make sure to initialize the target platform

---

gradle/longrunning-tests.gradle

[eclipse/xtext-extras#168] fixed deprecated gradle api usage for longrunning tests

[eclipse/xtext-extras#168] fixed deprecated gradle api usage for longrunning tests

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/quickfix/CreateMemberQuickfixes.java

- Ensure that all non-hidden leafs (not only the first one) are used
when composing the quickfix when hovering over a missing operator name.
- Implement corresponding QuickfixTest test cases:
missingLessThanMethod
missingGreaterThanMethod
missingDoubleLessThanMethod
missingDoubleGreaterThanMethod
missingTripleLessThanMethod
missingTripleGreaterThanMethod

[#561] Fix Xtend quickfixes on missing '<<','<<<','>>','>>>' operators.

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/hyperlinking/ConsoleHyperlinking.xtend
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/hyperlinking/ConsoleHyperlinking.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/hyperlinking/XtendFileHyperlink.java

- [538503] catch NumberFormatExceptions that can be caused by changed console content
- Fixed problem with non launch based stacktraces

Fixed two issues with Xtend File Hyperlinks in Consoles

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/XtendRenameRefactoringTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/refactoring/XtendRenameRefactoringTest.java

- Add testRenameXtendMember001 test case that is smaller and easier to
understand/debug than the testRenameXtendMember002 test case.

[#164] Add further test case reproducing the issue (currently ignored).

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/JavaDocContentAssistTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/contentassist/JavaDocContentAssistTest.java

- Modify the JavaDocContentAssist test cases to use explicit cursor
position markers instead of absolute cursor positions, since the
absolute cursor position can lead to different actual cursor positions
on different platforms (Linux/Windows) due to the different line
delimiters.

[#571] Fix failing JavaDocContentAssistTest on Windows platform.

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/AnnotationCompilerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/AnonymousClassCompilerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBug437678Test.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/XtendCompilerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/declaration/ConstantExpressionsInterpreterTest.xtend
org.eclipse.xtend.core.tests/testdata/test/Constants1.java
org.eclipse.xtend.core.tests/testdata/testdata/Constants1.java
org.eclipse.xtend.core.tests/testdata/types/StaticOuterClass.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/AnnotationCompilerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/AnonymousClassCompilerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBug437678Test.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/XtendCompilerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/declaration/ConstantExpressionsInterpreterTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/compiler/XtendGenerator.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/compiler/XtendGenerator.java

- Modify the XtendGenerator to generate the static and the final
modifiers in the right order (corresponding to the java language
specification) 'static final' instead of 'final static'.
- Adapt the corresponding test cases.

[#554] Ensure static and final modifiers generated in the right order.

---

Jenkinsfile
gradle/bootstrap-setup.gradle
gradle/upstream-repositories.gradle
releng/org.eclipse.xtend.maven.parent/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

Build steps defined in Jenkinsfile pass the built-in environment
variable 'JENKINS_URL' to the Gradle/Maven executions. This is evaluated
in the build scripts for upstream repository URLs. On Xtext JIPP this
will use upstream repos from JIPP. In local builds outside of Jenkins
the property defaults to Typefox CI like before.
Extend function jenkinsPipelineRepo() by upstreamBranch parameter and use this in the call.
Use jenkinsPipelineRepo() also for lsp4j.

[eclipse/xtext#1224] Detect local Jenkins environment

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java

XtendValidator: Remove com.google.common.collect.Sets.* unused import.

---

org.eclipse.xtend.ide/META-INF/MANIFEST.MF
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/wizards/AbstractNewXtendElementWizardPage.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/wizards/StubUtilityProxy.java
releng/org.eclipse.xtend.tycho.tests.parent/pom.xml

[#587] made calls to StubUtility possible with jdt 4.9 and 4.10
currently blocked by https://github.com/eclipse/xtext-xtend/pull/593

[#587] made calls to StubUtility possible with jdt 4.9 and 4.10

---

releng/org.eclipse.xtend.maven.parent/pom.xml

Renamed pom property ‚branch_url_segment‘ to ‚upstreamBranch‘ to align it with upstream-repositories.gradle

[eclipse/xtext-umbrella#65] Adjust upstream branch

---

releng/org.eclipse.xtend.tycho.tests.parent/pom.xml

[eclipse/xtext-eclipse#841] address removal of equinox.ds in platform 4.10

[eclipse/xtext-eclipse#841] address removal of equinox.ds in platform 4.10

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/richstring/RichStringEvaluationTest.java

[eclipse/xtext#1311] Make test independent from system encoding

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/ModifierValidationTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/ModifierValidationTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java

- Modifiy the Xtend ModifierValidator to provide a more meaningful
warning message in case of extension fields where the field name is not
set.
- Implement corresponding ModifierValidationTest test cases.

[#656] Improve unnecessary modifier warning message on extension fields.

---

1-gradle-build.sh
2-maven-build.sh
Jenkinsfile
org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/MavenVerifierUtil.java
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/aggregation/my-module/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/aggregation/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/aggregation/relativeoutput-module/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/encoding/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/filesystemaccess-client/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/filesystemaccess/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/macros/client/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/macros/lib/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/macros/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/multisources/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/simple/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/suppress_warnings_annotation/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/symlinks/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/trace_disabled/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/trace_enabled/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/trace_withtestsrc/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/withtestsrc/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/xtend-prefs-unused/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/xtend-prefs/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/xtenderrors/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/xtendwarnings/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/install_debug_info/simple_smap/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/install_debug_info/smap_multisource/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/install_debug_info/xtend_as_primary/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/install_debug_info/xtend_as_primary_with_synthetic_vars/pom.xml
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml

Moved common configuration to it-tests-parent
- dependency management with BOM
- dependency org.eclipse.xtend.lib
- plugin management of xtend-maven-plugin
- all projects have version 'IT-SNAPSHOT' now
- removed redundant `groupId` and `version` data inherited from parent
- pass `WORKSPACE` environment variable as system arg to surefire tests to resolve the local repo using this variable
Add shell scripts for convenient local execution

[#688] Simplify IT tests

---

org.eclipse.xtend.performance.tests/META-INF/MANIFEST.MF

set minimal mwe version to the one from oxygen

set minimal mwe version to the one from oxygen

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1394] bootstrap against 2.17.0.M2

[eclipse/xtext#1394] bootstrap against 2.17.0.M2

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1283] update to MWE 2.10
to not merge before MWE 2.10 is out

[eclipse/xtext#1283] update to MWE 2.10

---

gradle/upstream-repositories.gradle

workaround for jcenter maven central sync is too slow

add mavenCentral repository

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/ValidationIssue719Test.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/ValidationIssue719Test.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/IssueCodes.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendConfigurableIssueCodes.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/ValidationIssue719QuickFixTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/ValidationIssue719QuickFixTest.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/quickfix/XtendQuickfixProvider.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/validator/preferences/XtendValidatorConfigurationBlock.java

[Solution to Issue to #719 ](https://github.com/eclipse/xtext-xtend/issues/719)
If a type is named Abstractfoo but not declared abstract, an issue is raised.
The severity is configurable, default is warning. Also a quick fix is available to add the missing abstract modifier. If a the type is also declared final (but named Abstractfoo), the final modifier is removed, as it can be assumed that the abstract modifier is more important to the user (the type's name takes more time and thought to type in than the final keyword).

Solution Issue #719

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1405] bootstrap against 2.17.0

[eclipse/xtext#1405] bootstrap against 2.17.0

---

org.eclipse.xtend.ide/plugin.xml

The Xtend wizards are now showing in the Project Explorer New menu.

[issue#699] Add xtend wizard menu items to Project Explorer New menu

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBug437365Test.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBug465649Test.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBug437365Test.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBug465649Test.java

[eclipse/xtext-extras#394] fixed issues with nested inline feature calls

[eclipse/xtext-extras#394] fixed issues with nested inline feature calls

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/quickfix/XtendQuickfixProvider.java

Xtend Quickfix should also remove the unused imports and all writing accesses to the field #736
Signed-off-by: Lorenzo Addazi <addazi.lorenzo@gmail.com>

[issue#736] Xtend Quickfix should also remove the unused imports and all writing accesses to the field

---

README.md
gradle/bootstrap-setup.gradle
gradle/upstream-repositories.gradle
releng/org.eclipse.xtend.maven.parent/pom.xml
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.tycho.parent/pom.xml

Use https://ci.eclipse.org/xtext as default Jenkins URL

[eclipse/xtext#1424] Change default Jenkins

---

releng/org.eclipse.xtend.p2-repository/pom.xml
tycho-pom.xml

install is required to trigger the maven-antrun-plugin in
org.eclipse.xtend.p2-repository, which copies the resulting p2
repository to the target build folder. Without, the p2 repository is not
archived.

Change defaultGoal to install

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/DelegateCompilerTest.xtend
org.eclipse.xtend.core.tests/testdata/testdata/InterfaceWithStaticMethod.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/DelegateCompilerTest.java

[eclipse/xtext-core#1137] Filter static methods in Delegate active annotation

[eclipse/xtext-core#1137] Filter static methods in Delegate active annotation

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/buildpath/XtendClasspathContainer.java

[#804] fixed XtendClasspathContainer to comply with gradle folder structure.

[#804] fixed XtendClasspathContainer to comply with gradle folder structure.

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/AbstractXtendTestCase.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/AbstractXtendUITestCase.java

fixed determineJava11OrLater

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1473] bootstrap against 2.18

[eclipse/xtext#1473] bootstrap against 2.18

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/richstring/RichStringCompilerTest.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/RichStringValidationTest.java

speedup longrunning test: avoid extensive calls to classpathtypeprovider

speedup longrunning test: avoid extensive calls to classpathtypeprovider

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext1475] use 2019-09 in latest target platform

[eclipse/xtext1475] use 2019-09 in latest target platform

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/util/TemporaryFolder.java

[eclipse/xtext#1432] fixed implementation of TemporaryFolder.createTempFile

[eclipse/xtext#1432] fixed implementation of TemporaryFolder.createTempFile

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/AmbiguityGH389Test.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/AmbiguityValidationTests.xtend
org.eclipse.xtend.core.tests/suites/org/eclipse/xtend/core/tests/validation/AmbiguityValidationSuite.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/AmbiguityGH389Test.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/AmbiguityValidationTest.java

[eclipse/xtext-extras#389] Improved overload resolution for ambiguous constructor calls

[eclipse/xtext-extras#389] Improved overload resolution for ambiguous constructor calls

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1509] Bootstrap against 2.19.0.M1

[eclipse/xtext#1509] Bootstrap against 2.19.0.M1

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/hyperlinking/JavaDocHyperlinkingTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/hyperlinking/JavaDocHyperlinkingTest.java

- Modify the JavaDocHyperlinkingTest class to use the
org.eclipse.xtext.ui.testing.AbstractHyperlinkingTest API class instead
of the AbstractXtendUITestCase non API class.
- With this refactoring, the Xtend JavaDocHyperlinkingTest class becomes
consistent to the Domainmodel HyperlinkingTest test class.

Refactoring the JavaDocHyperlinkingTest test cases.

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-photon.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201809.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201812.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201903.target
releng/org.eclipse.xtend.target/org.eclipse.xtend.target-r201906.target

[eclipse/xtext#1279] use orbit simrel alias directly

[eclipse/xtext#1279] use orbit simrel alias directly

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/AmbiguityGH897Test.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/AmbiguityGH897Test.java

[eclipse/xtext-xtend#897] fixed problem with constructors and nested types

[eclipse/xtext-xtend#897] fixed problem with constructors and nested types

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/DelegateCompilerTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/DelegateCompilerTest.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/CodeGenerationContextImpl.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/TransformationContextImpl.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/ValidationContextImpl.java

[eclipse/xtext-lib#224] Stable method order when using Delegate annotation

[eclipse/xtext-lib#224] Stable method order when using Delegate 

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/contentassist/javadoc/XtendJavaDocContentAssistProcessor.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/editor/OverrideIndicatorRulerAction.java

[eclipse/xtext-eclipse#1155] Avoid unconditonal cast to IXtextDocument

[eclipse/xtext-eclipse#1155] Avoid unconditonal cast to IXtextDocument

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1537] bootstrap against 2.19.0

[eclipse/xtext#1537] bootstrap against 2.19.0

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1538] use eclipse 2019-12 in target

[eclipse/xtext#1538] use eclipse 2019-12 in target

---

org.eclipse.xtend.core/model/RichStrings.genmodel
org.eclipse.xtend.core/model/Xtend.genmodel

[eclipse/xtext#1550] set default compliance level to 8.0

[eclipse/xtext#1550] set default compliance level to 8.0

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#1560] bootstrap against 2.20.0.M1

[eclipse/xtext#1560] bootstrap against 2.20.0.M1

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/labeling/XtendDescriptionLabelProvider.java

Fix typo in the documentation of XtendDescriptionLabelProvider.

---

org.eclipse.xtend.core.tests/org.eclipse.xtend.core.tests.smoke-suites.launch

These changes were automatically applied to the launch configurations on
a fresh workspace setup.

[eclipse/xtext#1568] Remove Buildship classpath container

---

releng/org.eclipse.xtend.tycho.parent/pom.xml

avoid 'Directory is empty. Can't process' warning

avoid 'Directory is empty. Can't process' warning

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/AddJunitLibToClasspathQuickfixTest.xtend
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/buildpath/AbstractJunitLibClasspathAdderTestCase.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/buildpath/JunitLibClasspathAdderTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/buildpath/AbstractJunitLibClasspathAdderTestCase.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/buildpath/JunitLibClasspathAdderTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/AddJunitLibToClasspathQuickfixTest.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/buildpath/AbstractLibClasspathAdder.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/buildpath/Junit4LibClasspathAdder.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/buildpath/Junit5LibClasspathAdder.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/quickfix/XtendQuickfixProvider.java

[#919] Add quickfixes that adds JUnit 4 or 5 libs to the classpath.
Similar to the quickfix that adds Xtend libs, it will first check if the
project is a plugin project and add the required bundles to the `MANIFEST.MF`, if not it
will add a container entry to the `.classpath`. The quickfixes appear for errors on
import declaration that starts by "org.junit" or
"org.junit.jupiter".
Examples:
What I haven't done yet is show the quickfix only if JUnit4/5 can "really" be added to the classpath. Currently it still proposes the quickfix even if after applying it the error will persist.
Signed-off-by: Vivien Jovet <vivien.jovet@gmail.com>

[#919] Add quickfixes that adds JUnit 4 or 5 libs to the classpath

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1604] use 4.15 I-builds

[eclipse/xtext#1604] use 4.15 I-builds

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/AbstractXbaseEvaluationTest.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/formatting/preferences/AbstractProfileManager.java

The constructors of Wrapper classes have been deprecated. It is
recommended to use their static valueOf() method. For Boolean the
literals TRUE and FALSE can be used.

Refactor usage of Wrapper constructors to valueOf

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1685] use 4.16 ibuilds in latest target

[eclipse/xtext#1685] use 4.16 ibuilds in latest target

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/wizards/FieldInitializerUtil.java

change most of the direct calls to
org.eclipse.core.runtime.IAdaptable.getAdapter(Class<T>) to
org.eclipse.core.runtime.Adapters.adapt(Object, Class<T>) to also invite
registered AdapterFactories.
Signed-off-by: Mathias Rieder <mathias.rieder@gmail.com>

[eclipse/xtext-eclipse#1027] change getAdapter(..) to Adapters.adapt(..)

---

org.eclipse.xtend.ide.common/src-gen/org/eclipse/xtend/ide/common/contentassist/antlr/PartialXtendContentAssistParser.java

[eclipse/xtext-core#1418] removed redundant superinterface from generated ca parsers

[eclipse/xtext-core#1418] removed redundant superinterface from generated ca parsers

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/javaconverter/ConversionProblemsDialog.java

[eclipse/xtext#1738] use java.text.MessageFormat instead of com.ibm.icu.MessageFormat

[eclipse/xtext#1738] use java.text.MessageFormat instead of com.ibm.icu.MessageFormat

---

org.eclipse.xtend.ide/META-INF/MANIFEST.MF

[eclipse/xtext#1738] removed no longer needed icu dependency

[eclipse/xtext#1738] removed no longer needed icu dependency

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/compiler/batch/XtendBatchCompiler.java
org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/AbstractXtendCompilerMojo.java

Allow to pass arguments to the pre built Java compiler. By default disable annotation processing.
closes #1050

[#1050] Xtend precompile step should not blindly run annotations processors by default

---

org.eclipse.xtend.core.tests.java8/src/org/eclipse/xtend/core/tests/java8/validation/Java8ValidationTest.xtend
org.eclipse.xtend.core.tests.java8/xtend-gen/org/eclipse/xtend/core/tests/java8/validation/Java8ValidationTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java

[#1035] Missing validations in context of static interface methods

[#1035] Missing validations in context of static interface methods

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1784] use download.eclipse.org/releases/2020-09 in latest

[eclipse/xtext#1784] use download.eclipse.org/releases/2020-09 in latest

---

org.eclipse.xtend.core.tests.java8/src/org/eclipse/xtend/core/tests/java8/macro/DeclarationsTest.xtend
org.eclipse.xtend.core.tests.java8/xtend-gen/org/eclipse/xtend/core/tests/java8/macro/DeclarationsTest.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/declaration/DeclarationsTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/declaration/DeclarationsTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/declaration/XtendBasedDeclarations.xtend
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/declaration/ResolvedParameterImpl.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/declaration/XtendMethodDeclarationImpl.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/codebuilder/AbstractClassBuilder.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/codebuilder/AbstractCodeBuilder.java
org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/codebuilder/AbstractInterfaceBuilder.java

Added implementation for XtendMethodDeclaration.isDefault and getOverriddenOrImplemented
closes #1075

[#1075] Provide missing implementation for MethodDeclaration

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/EqualsWithNullMultiQuickfixTest.xtend
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/RemoveUnnecessaryModifiersMultiQuickfixTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/EqualsWithNullMultiQuickfixTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/RemoveUnnecessaryModifiersMultiQuickfixTest.java

- Cleaning up the EqualsWithNullMultiQuickfixTest and the
RemoveUnnecessaryModifiersMultiQuickfixTest tests cases.

[#1061] Improve the Xtend MultiQuickfix test cases.

---

org.eclipse.xtend.core/.settings/org.eclipse.xtend.shared.ui.prefs

removed obsolete org.eclipse.xtend.shared.ui.prefs

removed obsolete org.eclipse.xtend.shared.ui.prefs

---

org.eclipse.xtend.ide/src-gen/org/eclipse/xtend/ide/XtendExecutableExtensionFactory.java

Signed-off-by: Karsten Thoms <karsten.thoms@karakun.com>

Bug 568152 - Use FrameworkUtil#getBundle instead of Platform#getBundle

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/validation/AccessRestrictionInWorkspaceTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/validation/AccessRestrictionInWorkspaceTest.java

[eclipse/xtext-xtend#1132] do restriction checks also on type literal member feature calls

[eclipse/xtext-xtend#1132] do restriction checks also on type literal member feature calls

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/builder/JavaEditorExtension.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/builder/JavaEditorExtension.java

[#1135] fixed deadlock in tests (use real thread-safe boolean)
Fixes #1135

[#1135] fixed deadlock in tests (use real thread-safe boolean)

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/XtendActivator.java

It was enough to disable the event listener. No need to change the plugin.xml to come back to the previous state.
The dark theme support will be reconsidered for 2.25.

[#1143] Disable theme manager due to regression

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1885] update latest tp to 4.19-I-builds
DO NOT merge (yet) as 4.19-I-builds is not available yet

[eclipse/xtext#1885] update latest tp to 4.19-I-builds

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/EqualsWithNullMultiQuickfixTest.xtend
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/RemoveUnnecessaryModifiersMultiQuickfixTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/EqualsWithNullMultiQuickfixTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/RemoveUnnecessaryModifiersMultiQuickfixTest.java

- Update the Xtend EqualsWithNullMultiQuickfixTest and
RemoveUnnecessaryModifiersMultiQuickfixTest test cases to use a fix
lenght delimiter.
Signed-off-by: miklossy <miklossy@itemis.de>

https://github.com/eclipse/xtext-eclipse/issues/1505 Update Xtend tests.

---

org.eclipse.xtend.core.tests.java8/src/org/eclipse/xtend/core/tests/java8/compiler/CompilerBug410797Test.xtend
org.eclipse.xtend.core.tests.java8/src/org/eclipse/xtend/core/tests/java8/compiler/CompilerBug427637Test.xtend
org.eclipse.xtend.core.tests.java8/src/org/eclipse/xtend/core/tests/java8/compiler/Java8CompilerTest2.xtend
org.eclipse.xtend.core.tests.java8/xtend-gen/org/eclipse/xtend/core/tests/java8/compiler/CompilerBug410797Test.java
org.eclipse.xtend.core.tests.java8/xtend-gen/org/eclipse/xtend/core/tests/java8/compiler/CompilerBug427637Test.java
org.eclipse.xtend.core.tests.java8/xtend-gen/org/eclipse/xtend/core/tests/java8/compiler/Java8CompilerTest2.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/AbstractXtendCompilerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBug410797Test.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBug427637Test.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBugProtectedVisibilityTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/ImportManagerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/XtendCompilerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/AbstractReusableActiveAnnotationTests.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/AbstractXtendCompilerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBug410797Test.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBug427637Test.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBugProtectedVisibilityTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/ImportManagerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/XtendCompilerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/AbstractReusableActiveAnnotationTests.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/AbstractReusableActiveAnnotationTests.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/AbstractReusableActiveAnnotationTests.java

Cleaned up version of #1160 
fixes https://github.com/eclipse/xtext-xtend/issues/1029
Signed-off-by: Harald Fassler <harald.fassler+9974@gmail.com>

avoid unused imports (tests, cleaned up)

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1885] use 2021-03 in latest tp
DO not merge yet, 2021-03 is not available yet

[eclipse/xtext#1885] use 2021-03 in latest tp

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#1928] Bootstrap against MWE(2) 1.6.1/2.12.1 Final

[eclipse/xtext#1928] Bootstrap against MWE(2) 1.6.1/2.12.1 Final

---

maven-pom.xml

The version is already inherited. The 'prepare-release-branches' only
replaces the first version occurance. The redundant second entry has to
be removed.
See https://github.com/eclipse/xtext-umbrella/pull/252#issuecomment-791181220

[eclipse/xtext#1875] Remove redundant project version

---

Jenkinsfile

use 'unsuccessful' to catch all failure cases

use 'unsuccessful' to catch all failure cases

---

gradle/versions.gradle
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
releng/org.eclipse.xtend.tycho.parent/pom.xml

[eclipse/xtext#2002] bootstrap against Xtext 2.26.0.M2

[eclipse/xtext#2002] bootstrap against Xtext 2.26.0.M2

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#2038] build against 2022-06 in latest

[eclipse/xtext#2038] build against 2022-06 in latest

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/AnonymousClassCompilerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBugTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/ParameterizedInnerTypesCompilerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/XtendCompilerTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/AnonymousClassCompilerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBugTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/ParameterizedInnerTypesCompilerTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/XtendCompilerTest.java

[eclipse/xtext-xtend#1301] fix name clashes with anony. inner classes

[eclipse/xtext-xtend#1301] fix name clashes with anony. inner classes

---

releng/org.eclipse.xtend.target/org.eclipse.xtend.target-latest.target

[eclipse/xtext#2068] use 4.25 I-builds in latest

[eclipse/xtext#2068] use 4.25 I-builds in latest

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/formatting/preferences/AbstractModifyDialogTab.java

[#1362] remove workaround as classes in jdt are now no longer abstract

[#1362] remove workaround as classes in jdt are now no longer abstract

---

org.eclipse.xtend.m2e/META-INF/MANIFEST.MF
org.eclipse.xtend.m2e/src/org/eclipse/xtend/m2e/XtendProjectConfigurator.java

This PR aims to update `org.eclipse.xtend.m2e` Plugin to the M2E 2.0.1 release that is contributed to Eclipse 2022-09 M3 SimRel.
M2E 2.0 is a major release that has breaking changes in its API, that are incompatible with previous 1.x releases.
I updated the code and adjusted required bundle version ranges accordingly. Furthermore I update the target file to include the latest m2e release 2.0.1. That release is not yet in the 2022-09 release repo but will be with M3, so this change in advance should prevent trouble with the xText contribution.
I hope that is all correct, but please let me know if anything is wrong or missing.

Update to M2E 2.0

---

org.eclipse.xtend.core.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF
org.eclipse.xtend.examples/projects/xtend-examples/META-INF/MANIFEST.MF
org.eclipse.xtend.ide.swtbot.tests/META-INF/MANIFEST.MF
org.eclipse.xtend.ide.tests.data/META-INF/MANIFEST.MF
org.eclipse.xtend.ide.tests/META-INF/MANIFEST.MF

[eclipse/xtext#2125] set minimum junit version to 4.13.2

[eclipse/xtext#2125] set minimum junit version to 4.13.2
